// Carousel Batch 1: 34 Instagram carousels built to the craft rules in
// lib/carousel-reference.ts (CAROUSEL_ARCHETYPES / CAROUSEL_CRAFT_RULES),
// matching the founder voice established across the 1000-script library in
// lib/seed-data/octBatch.ts and siblings. Same persona: started consulting
// at 18-19 after failing entrance exams, runs a market-entry consulting
// practice (Upforge), 30+ clients across 15 industries and 6 countries.

import type { CarouselSeed } from "./carouselTypes";

export const CAROUSEL_BATCH_1_TAG = "carousel_batch_1_v1";

export const CAROUSEL_BATCH_1: CarouselSeed[] = [
  // 1 — listicle
  {
    title: "5 Pricing Mistakes Costing You 6-Figure Deals",
    pillar: "authority",
    contentType: "educational",
    archetype: "listicle",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Pricing Strategy",
    segment: "Framework Breakdown",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Deep navy solid background, bold white numerals as slide badges, clean sans headlines.",
    slides: [
      { role: "hook", headline: "7 pricing mistakes killing your consulting deals", supportingText: "Save this before your next proposal." },
      { role: "body", headline: "Mistake 1: quoting before you scope the problem", supportingText: "I lost a $12K deal doing exactly this in year one." },
      { role: "body", headline: "Mistake 2: pricing by the hour, not the outcome", supportingText: "Hourly caps your upside at your own ceiling." },
      { role: "body", headline: "Mistake 3: one flat price for every market", supportingText: "A Lagos entry and a Dubai entry carry different risk." },
      { role: "body", headline: "Mistake 4: no anchor tier in the proposal", supportingText: "Show 3 options or they anchor on the cheapest." },
      { role: "body", headline: "Mistake 5: discounting the second they hesitate", supportingText: "Hesitation usually means unclear value, not high price." },
      { role: "body", headline: "Mistake 6: no kill fee clause for scope changes", supportingText: "Scope always expands — protect the first 20 hours." },
      { role: "body", headline: "Mistake 7: never repricing after year one", supportingText: "I 3x'd my retainer between client 5 and client 25." },
      { role: "cta", headline: "Save this for your next pricing conversation", supportingText: "" },
    ],
  },
  // 2 — myth_bust
  {
    title: "The Market Entry Myths That Cost Founders 6 Months",
    pillar: "authority",
    contentType: "educational",
    archetype: "myth_bust",
    ctaType: "share",
    funnelStage: "tofu",
    topicTag: "Market Entry",
    segment: "Myth Bust",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Deep red-to-black gradient, bold crossed-out myth line above a clean truth line.",
    slides: [
      { role: "hook", headline: "Market entry is full of expensive myths", supportingText: "Here's what's actually true." },
      { role: "body", headline: "Myth: a great product sells itself abroad", supportingText: "Truth: distribution beats product in every new market I've audited." },
      { role: "body", headline: "Myth: your home-market pricing will travel", supportingText: "Truth: I've seen founders lose 40% of buyers on price alone." },
      { role: "body", headline: "Myth: you need a local office on day one", supportingText: "Truth: a local partner beats a lease for your first 12 months." },
      { role: "body", headline: "Myth: regulations are mostly paperwork", supportingText: "Truth: I've watched a skipped filing delay a launch by 6 months." },
      { role: "body", headline: "Myth: more markets at once means faster growth", supportingText: "Truth: spreading thin is the #1 killer, not competition." },
      { role: "body", headline: "Myth: local competitors don't matter yet", supportingText: "Truth: if you can't name your 3 closest rivals, you're not ready." },
      { role: "cta", headline: "Share this with someone about to expand blind", supportingText: "" },
    ],
  },
  // 3 — tutorial
  {
    title: "How to Onboard a New Consulting Client (9 Steps)",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Client Onboarding",
    segment: "SOP Walkthrough",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard texture with marker-style numbered steps, hand-drawn arrows between slides.",
    slides: [
      { role: "hook", headline: "How to onboard a client in 7 steps", supportingText: "The exact SOP I use for every new engagement." },
      { role: "body", headline: "Step 1: send the contract within 24 hours", supportingText: "Momentum dies the moment a signed deal goes cold." },
      { role: "body", headline: "Step 2: collect a kickoff questionnaire first", supportingText: "No kickoff call until I have this back." },
      { role: "body", headline: "Step 3: run the kickoff call by day 2", supportingText: "Early clarity prevents 80% of scope fights later." },
      { role: "body", headline: "Step 4: set the communication channel in writing", supportingText: "One tool, one cadence — decided before chaos decides for you." },
      { role: "body", headline: "Step 5: share a one-page scope recap after the call", supportingText: "If it's not written down, it didn't happen." },
      { role: "body", headline: "Step 6: book the first milestone check-in immediately", supportingText: "Put it on the calendar before the excitement fades." },
      { role: "body", headline: "Step 7: send a 48-hour check-in message", supportingText: "Catches confusion before it becomes resentment." },
      { role: "cta", headline: "Save this for when step 4 trips you up", supportingText: "" },
    ],
  },
  // 4 — single_concept
  {
    title: "Pick One Beachhead Before You Touch a Second Market",
    pillar: "authority",
    contentType: "authority",
    archetype: "single_concept",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Market Strategy",
    segment: "",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Charcoal solid background, single bold line per slide, generous whitespace for an editorial feel.",
    slides: [
      { role: "hook", headline: "Pick one beachhead before a second market", supportingText: "This single decision fixes most failed launches." },
      { role: "body", headline: "87% of the MSMEs I've audited make this mistake", supportingText: "Three markets at once, mastery in none." },
      { role: "body", headline: "A beachhead is one narrow segment you can dominate", supportingText: "Not a country. Not an industry. One segment." },
      { role: "body", headline: "Dominance signals to the next segment over", supportingText: "Word travels inside tight buyer networks fast." },
      { role: "body", headline: "Spreading thin isn't ambition — it's avoidance", supportingText: "It feels like progress while nothing actually closes." },
      { role: "body", headline: "I've seen one focused segment outgrow five scattered ones", supportingText: "Same budget, wildly different outcome." },
      { role: "cta", headline: "Save this before you expand to market two", supportingText: "" },
    ],
  },
  // 5 — story_arc
  {
    title: "I Failed My Entrance Exams at 18",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Journey",
    segment: "Origin Story",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Warm amber-to-navy gradient, intimate handwritten-feel accent font for the lesson slide.",
    slides: [
      { role: "hook", headline: "At 18, I failed my entrance exams", supportingText: "Not a near-miss. A real, public failure." },
      { role: "body", headline: "Everyone I knew had a plan except me", supportingText: "For a few months I barely left the house." },
      { role: "body", headline: "Then I picked up an old case study book", supportingText: "It had sat on a shelf since 4th grade." },
      { role: "body", headline: "I read the whole thing in one week", supportingText: "Something clicked that school never gave me." },
      { role: "body", headline: "I cold-messaged a local shop owner with one idea", supportingText: "No portfolio. No credentials. Just the idea." },
      { role: "body", headline: "That idea became my first paid consulting project", supportingText: "₹8,000. I still remember the exact number." },
      { role: "body", headline: "Two years later: 30+ clients, 15 industries, 6 countries", supportingText: "Started from a failed exam and a borrowed book." },
      { role: "cta", headline: "Follow to see the rest of the build", supportingText: "" },
    ],
  },
  // 6 — comparison
  {
    title: "Retainer vs Project Pricing: Which One Actually Pays",
    pillar: "authority",
    contentType: "educational",
    archetype: "comparison",
    ctaType: "comment",
    funnelStage: "mofu",
    topicTag: "Pricing Models",
    segment: "",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Split-screen solid background, left panel muted gray for Project, right panel deep green for Retainer.",
    slides: [
      { role: "hook", headline: "Retainer vs project — which one pays more?", supportingText: "I've run both for years. Here's the real answer." },
      { role: "body", headline: "Project pricing: fast to sell, fast to end", supportingText: "Clear scope, clear finish line, clear invoice." },
      { role: "body", headline: "Project pricing caps your income at your calendar", supportingText: "No project running means no revenue running." },
      { role: "body", headline: "Retainer pricing: harder to sell, compounds over time", supportingText: "You're asking for trust before you've proven value." },
      { role: "body", headline: "Retainer pricing smooths cash flow month to month", supportingText: "My first 12-month retainer changed how I planned expenses." },
      { role: "body", headline: "The real answer: project to earn trust, retainer to scale", supportingText: "I moved every long-term client to retainer by month 4." },
      { role: "cta", headline: "Comment PROJECT or RETAINER — what's your model", supportingText: "" },
    ],
  },
  // 7 — listicle
  {
    title: "6 Red Flags in a Local Market Partner",
    pillar: "authority",
    contentType: "educational",
    archetype: "listicle",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Local Partnerships",
    segment: "Checklist",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Warning-red accent badges on a deep gray solid background, numbered checklist layout.",
    slides: [
      { role: "hook", headline: "6 red flags in a local market partner", supportingText: "Save this before you sign anything." },
      { role: "body", headline: "Red flag 1: no prior clients they'll name", supportingText: "If they won't introduce a reference, walk away." },
      { role: "body", headline: "Red flag 2: vague on their own commission structure", supportingText: "Unclear math now means disputes later." },
      { role: "body", headline: "Red flag 3: promises exclusivity before any results", supportingText: "Exclusivity should be earned, not pitched upfront." },
      { role: "body", headline: "Red flag 4: no local registration of their own", supportingText: "A real partner is a real, registered business." },
      { role: "body", headline: "Red flag 5: pushes you to skip legal review", supportingText: "I once saw this clause hide a 15% kickback." },
      { role: "body", headline: "Red flag 6: can't explain the regulatory landscape simply", supportingText: "If they can't explain it, they don't actually know it." },
      { role: "cta", headline: "Save this for your next partnership call", supportingText: "" },
    ],
  },
  // 8 — myth_bust
  {
    title: "Regulatory Compliance Myths That Delay Launches",
    pillar: "authority",
    contentType: "educational",
    archetype: "myth_bust",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Regulatory Compliance",
    segment: "Myth Bust",
    backgroundStyle: "screenshot",
    backgroundCategory: "",
    designNotes: "Mock compliance-checklist screenshot background with a frosted overlay card for each myth/truth pair.",
    slides: [
      { role: "hook", headline: "Compliance myths that quietly delay launches", supportingText: "Every one of these has cost a client real time." },
      { role: "body", headline: "Myth: compliance is mostly paperwork", supportingText: "Truth: one skipped filing delayed a client 6 months." },
      { role: "body", headline: "Myth: your lawyer at home covers you abroad", supportingText: "Truth: local counsel catches what general counsel misses." },
      { role: "body", headline: "Myth: you can register the entity after launch", supportingText: "Truth: most markets require it before you invoice a single customer." },
      { role: "body", headline: "Myth: small teams get overlooked by regulators", supportingText: "Truth: I've seen a 4-person team fined faster than a 400-person one." },
      { role: "body", headline: "Myth: compliance costs are fixed once you budget them", supportingText: "Truth: I always budget 20% above the quoted legal estimate." },
      { role: "cta", headline: "Save this before you file anything new", supportingText: "" },
    ],
  },
  // 9 — story_arc
  {
    title: "My First Client Almost Didn't Happen",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Journey",
    segment: "Case Study",
    backgroundStyle: "photo",
    backgroundCategory: "coffee_shop",
    designNotes: "Warm coffee-shop photo background, 50% dark scrim for legibility, cream serif headline font.",
    slides: [
      { role: "hook", headline: "My first client almost never happened", supportingText: "One rejected DM changed everything." },
      { role: "body", headline: "I messaged 40 local businesses that first month", supportingText: "39 never replied. One did." },
      { role: "body", headline: "She almost said no — I had zero case studies", supportingText: "I offered to work for free if it didn't work." },
      { role: "body", headline: "I spent a week mapping her 3 local competitors", supportingText: "No one had ever shown her that before." },
      { role: "body", headline: "Her foot traffic moved before I even billed her", supportingText: "That was the moment I knew this could be real." },
      { role: "body", headline: "She became my first paying client the next week", supportingText: "₹8,000 for work that would now cost 10x that." },
      { role: "body", headline: "She's still a client, 3 years and 2 markets later", supportingText: "One rejected-sounding DM built the whole practice." },
      { role: "cta", headline: "Follow for more of how this practice got built", supportingText: "" },
    ],
  },
  // 10 — tutorial
  {
    title: "The Discovery Call Framework I Use On Every Lead",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Sales Process",
    segment: "Framework Breakdown",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard marker diagram with a simple call-flow arrow connecting each numbered step.",
    slides: [
      { role: "hook", headline: "My discovery call framework, step by step", supportingText: "Same 6 steps on every single lead call." },
      { role: "body", headline: "Step 1: ask what they've already tried", supportingText: "Tells you what NOT to pitch." },
      { role: "body", headline: "Step 2: ask what happens if nothing changes", supportingText: "This is where urgency reveals itself, not forced." },
      { role: "body", headline: "Step 3: ask who else is involved in the decision", supportingText: "Skip this and your proposal stalls with a ghost approver." },
      { role: "body", headline: "Step 4: name the real problem back to them", supportingText: "Clients buy clarity before they buy a plan." },
      { role: "body", headline: "Step 5: give one free insight on the call", supportingText: "Proof beats promises every time." },
      { role: "body", headline: "Step 6: set the next step before you hang up", supportingText: "A call without a date attached dies in their inbox." },
      { role: "cta", headline: "Save this for your next discovery call", supportingText: "" },
    ],
  },
  // 11 — single_concept
  {
    title: "The 3 Levels of Market Research",
    pillar: "authority",
    contentType: "educational",
    archetype: "single_concept",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Market Research",
    segment: "",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Deep teal solid background, large numeral per slide, minimal supporting text.",
    slides: [
      { role: "hook", headline: "There are 3 levels of market research", supportingText: "Most founders never leave level one." },
      { role: "body", headline: "Level 1: Googling your competitors", supportingText: "Everyone does this. It tells you nothing actionable." },
      { role: "body", headline: "Level 2: interviewing 10 people in the market", supportingText: "Now you have real objections to design around." },
      { role: "body", headline: "Level 3: running a $500 test campaign before building", supportingText: "The only level that tells you if people will pay." },
      { role: "body", headline: "Most founders stop at level 1 and wonder why", supportingText: "Then they launch blind and call it bad luck." },
      { role: "body", headline: "Level 3 cost one client $500 and saved them $40K", supportingText: "It killed an idea before the build budget was spent." },
      { role: "cta", headline: "Save this before your next market research push", supportingText: "" },
    ],
  },
  // 12 — before_after
  {
    title: "Scope Creep: Before and After One Clause",
    pillar: "authority",
    contentType: "educational",
    archetype: "before_after",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Project Management",
    segment: "Before/After",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Muted gray-to-gold gradient, split layout contrasting chaotic before with clean after list.",
    slides: [
      { role: "hook", headline: "Scope creep to zero disputes in one clause", supportingText: "One line changed how every project ends now." },
      { role: "body", headline: "Before: clients kept adding 'one more thing'", supportingText: "Free requests stacked until margins disappeared." },
      { role: "body", headline: "Before: I said yes to protect the relationship", supportingText: "Protecting the relationship was quietly bankrupting the project." },
      { role: "body", headline: "The fix: a written scope-change clause in every contract", supportingText: "Extra requests get a quote, not a quiet yes." },
      { role: "body", headline: "After: clients respect the scope more, not less", supportingText: "Clear boundaries read as professionalism, not pettiness." },
      { role: "body", headline: "After: average project margin went up 22%", supportingText: "Same work, fewer unpaid extras eating into it." },
      { role: "cta", headline: "Save this before you send your next contract", supportingText: "" },
    ],
  },
  // 13 — listicle
  {
    title: "5 Things to Check Before Mapping Competitors",
    pillar: "authority",
    contentType: "educational",
    archetype: "listicle",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Competitive Analysis",
    segment: "Checklist",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Clean off-white solid background, bold black numerals, minimal icon per slide.",
    slides: [
      { role: "hook", headline: "5 things before you map competitors", supportingText: "Skip these and the mapping is useless." },
      { role: "body", headline: "1. Define your exact segment first", supportingText: "Broad 'competitors' means a useless, endless list." },
      { role: "body", headline: "2. Check their pricing, not just their product", supportingText: "Price tells you who they're really built for." },
      { role: "body", headline: "3. Look at their reviews, not their ads", supportingText: "Ads show intent. Reviews show reality." },
      { role: "body", headline: "4. Track how long they've operated locally", supportingText: "A 6-month player and a 6-year player behave differently." },
      { role: "body", headline: "5. Map their weakest customer complaint", supportingText: "That complaint is your opening, not their product." },
      { role: "cta", headline: "Save this before your next competitor audit", supportingText: "" },
    ],
  },
  // 14 — comparison
  {
    title: "DIY Market Entry vs Hiring a Consultant",
    pillar: "authority",
    contentType: "educational",
    archetype: "comparison",
    ctaType: "link",
    funnelStage: "bofu",
    topicTag: "Hiring A Consultant",
    segment: "",
    backgroundStyle: "minimalist",
    backgroundCategory: "",
    designNotes: "Minimalist two-column layout, thin dividing line, restrained type with one accent color.",
    slides: [
      { role: "hook", headline: "DIY market entry vs hiring a consultant", supportingText: "The honest tradeoffs, no sales pitch." },
      { role: "body", headline: "DIY: cheaper upfront, slower to validate", supportingText: "You pay in months instead of dollars." },
      { role: "body", headline: "DIY: you learn the market firsthand", supportingText: "Real edge, if you survive the learning curve." },
      { role: "body", headline: "Consultant: faster validation, costs more upfront", supportingText: "You're buying someone else's past mistakes." },
      { role: "body", headline: "Consultant: brings competitor and pricing data day one", supportingText: "Data you'd otherwise spend months collecting." },
      { role: "body", headline: "The real question: how much does 6 months cost you", supportingText: "If delay is expensive, the math usually favors expert help." },
      { role: "cta", headline: "Link in bio to book a free fit call", supportingText: "" },
    ],
  },
  // 15 — tutorial
  {
    title: "How to Write a Proposal Clients Actually Sign",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Proposal Writing",
    segment: "Framework Breakdown",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard with a sticky-note style layout, one note per proposal section.",
    slides: [
      { role: "hook", headline: "How to write a proposal clients sign fast", supportingText: "The 7-section structure I never deviate from." },
      { role: "body", headline: "Section 1: restate their problem, in their words", supportingText: "They need to feel heard before they read a plan." },
      { role: "body", headline: "Section 2: show the cost of doing nothing", supportingText: "Urgency belongs in the proposal, not just the call." },
      { role: "body", headline: "Section 3: lay out 3 pricing tiers, not one", supportingText: "A middle tier anchors the decision toward yes." },
      { role: "body", headline: "Section 4: include a clear timeline with milestones", supportingText: "Vague timelines read as vague thinking." },
      { role: "body", headline: "Section 5: add 2 relevant case studies, not 10", supportingText: "Relevance beats volume every time." },
      { role: "body", headline: "Section 6: state exactly what happens after signing", supportingText: "Remove every bit of post-signature uncertainty." },
      { role: "body", headline: "Section 7: a deadline on the proposal itself", supportingText: "No deadline means no urgency to decide." },
      { role: "cta", headline: "Save this for your next proposal draft", supportingText: "" },
    ],
  },
  // 16 — quote_chain
  {
    title: "What I'd Tell the 18-Year-Old Who Failed His Exams",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "quote_chain",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Mindset",
    segment: "Quote Chain",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Soft charcoal-to-amber gradient, one large serif statement per slide, no supporting text clutter.",
    slides: [
      { role: "hook", headline: "What I'd tell the 18-year-old who failed", supportingText: "" },
      { role: "body", headline: "The exam result isn't the whole story", supportingText: "" },
      { role: "body", headline: "A plan falling apart isn't the same as failing", supportingText: "" },
      { role: "body", headline: "You don't need a degree to start", supportingText: "You need one client who says yes." },
      { role: "body", headline: "Everyone ahead of you started somewhere worse", supportingText: "" },
      { role: "body", headline: "Two years changes more than you think", supportingText: "30+ clients, 15 industries, 6 countries — from zero." },
      { role: "cta", headline: "Follow for more of the journey", supportingText: "" },
    ],
  },
  // 17 — myth_bust
  {
    title: "Client Red Flags Everyone Ignores Until It's Too Late",
    pillar: "authority",
    contentType: "educational",
    archetype: "myth_bust",
    ctaType: "share",
    funnelStage: "tofu",
    topicTag: "Client Vetting",
    segment: "Myth Bust",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Deep plum solid background, strikethrough myth text above a bold truth statement.",
    slides: [
      { role: "hook", headline: "Client red flags everyone ignores too long", supportingText: "I've learned every one of these the hard way." },
      { role: "body", headline: "Myth: a fast 'yes' means an easy client", supportingText: "Truth: fast yeses often mean fast, vague expectations too." },
      { role: "body", headline: "Myth: negotiating hard on price is just business", supportingText: "Truth: it usually predicts how they'll treat every deliverable." },
      { role: "body", headline: "Myth: 'we move fast' is a compliment", supportingText: "Truth: it's often code for no process and constant fire drills." },
      { role: "body", headline: "Myth: unresponsive during sales will improve after signing", supportingText: "Truth: it almost never does. It gets worse." },
      { role: "body", headline: "Myth: every client is worth landing", supportingText: "Truth: I've fired more clients than I regret losing." },
      { role: "cta", headline: "Share this with someone vetting a new client", supportingText: "" },
    ],
  },
  // 18 — before_after
  {
    title: "My Pricing Before and After Client 10",
    pillar: "authority",
    contentType: "authority",
    archetype: "before_after",
    ctaType: "link",
    funnelStage: "bofu",
    topicTag: "Pricing Strategy",
    segment: "Before/After",
    backgroundStyle: "screenshot",
    backgroundCategory: "",
    designNotes: "Mock invoice/spreadsheet screenshot background, bold overlay numbers contrasting old vs new rates.",
    slides: [
      { role: "hook", headline: "My pricing before and after client 10", supportingText: "The jump happened faster than I expected." },
      { role: "body", headline: "Before: ₹8,000 flat for a full market audit", supportingText: "Priced out of fear, not out of value." },
      { role: "body", headline: "Before: I quoted the same number to everyone", supportingText: "No tiers, no differentiation, no upside." },
      { role: "body", headline: "The shift: I started pricing the outcome, not the hours", supportingText: "A client's revenue at stake changed everything about the number." },
      { role: "body", headline: "After: ₹85,000 for the same core deliverable", supportingText: "Repackaged with tiers and a clear ROI case." },
      { role: "body", headline: "After: fewer clients, same revenue, far less burnout", supportingText: "6 retainer clients now outperform 20 one-off projects." },
      { role: "cta", headline: "Link in bio for the pricing framework I use now", supportingText: "" },
    ],
  },
  // 19 — story_arc
  {
    title: "Expanding Into a 15th Industry Nearly Broke Me",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "follow",
    funnelStage: "mofu",
    topicTag: "Founder Journey",
    segment: "Case Study",
    backgroundStyle: "photo",
    backgroundCategory: "skyline",
    designNotes: "City skyline photo background at dusk, dark scrim, ambition-coded mood for the turning point slides.",
    slides: [
      { role: "hook", headline: "Industry 15 nearly broke the practice", supportingText: "The hardest expansion so far, by far." },
      { role: "body", headline: "I said yes before I understood the industry", supportingText: "Pride said yes faster than preparation did." },
      { role: "body", headline: "Week 2: learning the industry on the client's dime", supportingText: "That feeling is as bad as it sounds." },
      { role: "body", headline: "I almost refunded the deposit and walked away", supportingText: "Instead I spent a weekend interviewing 8 people in the space." },
      { role: "body", headline: "Those 8 conversations rebuilt the entire strategy", supportingText: "Turns out the client's own assumptions were half wrong too." },
      { role: "body", headline: "The project became one of my strongest case studies", supportingText: "Discomfort, it turns out, was the actual qualification." },
      { role: "body", headline: "Lesson: competence comes from the work, not before it", supportingText: "Waiting to feel ready would have meant never starting." },
      { role: "cta", headline: "Follow for more lessons from inside the work", supportingText: "" },
    ],
  },
  // 20 — myth_bust
  {
    title: "Negotiation Myths Killing Your Margins",
    pillar: "authority",
    contentType: "educational",
    archetype: "myth_bust",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Negotiation",
    segment: "Myth Bust",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Forest green solid background, bold myth/truth typographic contrast, no imagery.",
    slides: [
      { role: "hook", headline: "Negotiation myths quietly killing your margins", supportingText: "Unlearn these before your next deal." },
      { role: "body", headline: "Myth: the first number sets the real price", supportingText: "Truth: the first number only sets the anchor, not the floor." },
      { role: "body", headline: "Myth: meeting in the middle is always fair", supportingText: "Truth: it only works if your first number was ambitious enough." },
      { role: "body", headline: "Myth: silence after a quote is a bad sign", supportingText: "Truth: silence is often just them doing the math — let it sit." },
      { role: "body", headline: "Myth: discounting saves a deal that's about to die", supportingText: "Truth: it usually just delays the same objection, cheaper." },
      { role: "body", headline: "Myth: you have to justify every number you give", supportingText: "Truth: over-explaining price signals you don't believe it yourself." },
      { role: "cta", headline: "Save this before your next price negotiation", supportingText: "" },
    ],
  },
  // 21 — tutorial
  {
    title: "How to Size a Market in 5 Steps",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Market Sizing",
    segment: "Framework Breakdown",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard with a funnel diagram narrowing from TAM to SAM to SOM across slides.",
    slides: [
      { role: "hook", headline: "How to size a market in 5 steps", supportingText: "The exact process behind every market sizing deck I build." },
      { role: "body", headline: "Step 1: define TAM using public industry data", supportingText: "This number impresses investors, nothing else." },
      { role: "body", headline: "Step 2: narrow to SAM using your actual channels", supportingText: "If you can't reach them, they don't count yet." },
      { role: "body", headline: "Step 3: narrow to SOM using realistic capture rate", supportingText: "I cap year-one capture at 2-3% for any new entrant." },
      { role: "body", headline: "Step 4: stress-test SOM against your delivery capacity", supportingText: "A number you can't fulfill isn't a real target." },
      { role: "body", headline: "Step 5: revisit the sizing every 2 quarters", supportingText: "Markets move faster than the deck that first sized them." },
      { role: "cta", headline: "Save this for your next market sizing exercise", supportingText: "" },
    ],
  },
  // 22 — single_concept
  {
    title: "Budget 90 Days of Distribution Before Brand Spend",
    pillar: "authority",
    contentType: "authority",
    archetype: "single_concept",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Expansion Planning",
    segment: "",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Slate-to-amber gradient, single statement per slide, large numerals for the day count.",
    slides: [
      { role: "hook", headline: "Budget 90 days of distribution before brand spend", supportingText: "The sequence most launches get backwards." },
      { role: "body", headline: "Distribution isn't competition — it's the real #1 killer", supportingText: "You can lose with a better product and still lose." },
      { role: "body", headline: "A great product nobody can find doesn't sell", supportingText: "Discovery has to exist before conversion can." },
      { role: "body", headline: "90 days is enough to be findable, not famous", supportingText: "Familiarity, not virality, is the first-quarter goal." },
      { role: "body", headline: "Brand marketing on zero distribution burns the budget", supportingText: "You're paying to be seen with nowhere to land." },
      { role: "body", headline: "Get found first. Get loved second.", supportingText: "The order is not optional." },
      { role: "cta", headline: "Save this before your next market launch", supportingText: "" },
    ],
  },
  // 23 — comparison
  {
    title: "Hourly vs Value-Based Pricing for Consultants",
    pillar: "authority",
    contentType: "educational",
    archetype: "comparison",
    ctaType: "link",
    funnelStage: "bofu",
    topicTag: "Pricing Models",
    segment: "",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Split solid background, muted gray for Hourly, warm gold for Value-Based.",
    slides: [
      { role: "hook", headline: "Hourly vs value pricing — which actually scales", supportingText: "Only one of these grew my income past a ceiling." },
      { role: "body", headline: "Hourly: easy to explain, easy to underprice yourself", supportingText: "You're selling time, the one thing that never scales." },
      { role: "body", headline: "Hourly punishes you for getting faster at the work", supportingText: "Efficiency should raise income, not cut your invoice." },
      { role: "body", headline: "Value-based: priced on the client's outcome, not your clock", supportingText: "A $40K problem can justify a $6K fee easily." },
      { role: "body", headline: "Value-based requires real confidence in your results", supportingText: "You need case studies before clients believe the number." },
      { role: "body", headline: "I moved fully to value pricing by client 15", supportingText: "Revenue doubled on roughly the same workload." },
      { role: "cta", headline: "Link in bio for my value pricing worksheet", supportingText: "" },
    ],
  },
  // 24 — story_arc
  {
    title: "The Client Who Almost Fired Me — And Didn't",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "link",
    funnelStage: "bofu",
    topicTag: "Founder Journey",
    segment: "Case Study",
    backgroundStyle: "photo",
    backgroundCategory: "window_light",
    designNotes: "Soft side-lit window-light photo background, calm mood, gold accent type for the turning point line.",
    slides: [
      { role: "hook", headline: "This client almost fired me in month one", supportingText: "What changed her mind is why I still work this way." },
      { role: "body", headline: "Her first market entry attempt failed before me", supportingText: "She came in skeptical, understandably." },
      { role: "body", headline: "Week 3: her numbers still hadn't moved", supportingText: "She scheduled a call I knew wasn't good news." },
      { role: "body", headline: "I showed up with the data, not an excuse", supportingText: "Three reasons it hadn't worked yet, in writing." },
      { role: "body", headline: "She gave me 30 more days instead of ending it", supportingText: "Transparency bought the time the results hadn't yet." },
      { role: "body", headline: "By day 45, her first new-market sale landed", supportingText: "The turning point wasn't the strategy — it was the honesty." },
      { role: "body", headline: "She's referred 4 other founders since", supportingText: "The relationship outlasted the rough start by years." },
      { role: "cta", headline: "Link in bio to start your own engagement", supportingText: "" },
    ],
  },
  // 25 — listicle
  {
    title: "6 Cold Outreach Mistakes Killing Your Reply Rate",
    pillar: "authority",
    contentType: "educational",
    archetype: "listicle",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Client Acquisition",
    segment: "Checklist",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Bold electric blue solid background, bold numeral badges, high contrast white type.",
    slides: [
      { role: "hook", headline: "6 cold outreach mistakes killing your replies", supportingText: "I sent 40 of these messages before I fixed them." },
      { role: "body", headline: "Mistake 1: opening with 'I help businesses grow'", supportingText: "So does everyone else in their inbox that week." },
      { role: "body", headline: "Mistake 2: pitching before you've said anything specific", supportingText: "Specificity is the only thing that earns a reply." },
      { role: "body", headline: "Mistake 3: a message with zero clear ask", supportingText: "If they don't know what you want, they won't reply." },
      { role: "body", headline: "Mistake 4: sending the same message to everyone", supportingText: "Generic reads as mass-sent in under 2 seconds." },
      { role: "body", headline: "Mistake 5: following up once and giving up", supportingText: "Most of my replies came on message 2 or 3." },
      { role: "body", headline: "Mistake 6: no proof point in the first message", supportingText: "One real result beats ten adjectives." },
      { role: "cta", headline: "Save this before your next outreach batch", supportingText: "" },
    ],
  },
  // 26 — myth_bust
  {
    title: "Myths About the Consulting Industry, Busted",
    pillar: "authority",
    contentType: "educational",
    archetype: "myth_bust",
    ctaType: "share",
    funnelStage: "tofu",
    topicTag: "Consulting Industry",
    segment: "Myth Bust",
    backgroundStyle: "minimalist",
    backgroundCategory: "",
    designNotes: "Minimalist cream background, thin black rule dividing myth from truth, restrained type.",
    slides: [
      { role: "hook", headline: "Myths about consulting that need to die", supportingText: "A few of these cost me real money to unlearn." },
      { role: "body", headline: "Myth: you need an MBA to be credible", supportingText: "Truth: clients hire results, not credentials, every time." },
      { role: "body", headline: "Myth: you need a big network to start", supportingText: "Truth: my first client came from a cold DM, not a network." },
      { role: "body", headline: "Myth: consultants are just expensive opinions", supportingText: "Truth: good consulting is applied research, not opinion." },
      { role: "body", headline: "Myth: you have to niche down to one industry", supportingText: "Truth: a transferable framework beats a single-industry label." },
      { role: "body", headline: "Myth: consulting doesn't scale past your own hours", supportingText: "Truth: packaged frameworks and retainers scale it just fine." },
      { role: "cta", headline: "Share this with someone considering consulting", supportingText: "" },
    ],
  },
  // 27 — before_after
  {
    title: "My Contracts Before and After One Bad Client",
    pillar: "authority",
    contentType: "educational",
    archetype: "before_after",
    ctaType: "save",
    funnelStage: "bofu",
    topicTag: "Contracts & Scope",
    segment: "Before/After",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Crisp white solid background with a thin red strike-through motif for every 'before' clause.",
    slides: [
      { role: "hook", headline: "My contracts before and after one bad client", supportingText: "One painful project rewrote every agreement since." },
      { role: "body", headline: "Before: a vague one-page scope summary", supportingText: "Easy to sign, impossible to enforce." },
      { role: "body", headline: "Before: no kill fee if the client paused mid-project", supportingText: "A 3-month pause once cost me the entire margin." },
      { role: "body", headline: "After: scope defined in deliverables, not hours", supportingText: "Everyone knows exactly what 'done' looks like." },
      { role: "body", headline: "After: a 25% kill fee on any pause or cancel", supportingText: "It's never once scared off a serious client." },
      { role: "body", headline: "After: payment milestones tied to delivery, not dates", supportingText: "No more chasing invoices on a calendar that slipped." },
      { role: "cta", headline: "Save this before you send your next contract", supportingText: "" },
    ],
  },
  // 28 — single_concept
  {
    title: "Stop Being 'A Consultant' — Be The Name For One Thing",
    pillar: "authority",
    contentType: "authority",
    archetype: "single_concept",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Positioning",
    segment: "",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Bold magenta-to-navy gradient, one declarative sentence per slide, oversized type.",
    slides: [
      { role: "hook", headline: "Stop being 'a consultant' — own one thing", supportingText: "Positioning fixed more of my sales than skill ever did." },
      { role: "body", headline: "Generic positioning gets generic inbound", supportingText: "Vague offers attract vague budgets." },
      { role: "body", headline: "I used to say 'I help businesses grow'", supportingText: "Nobody remembered that sentence five minutes later." },
      { role: "body", headline: "Now I say 'market entry for MSMEs going cross-border'", supportingText: "Narrower, and somehow easier to sell." },
      { role: "body", headline: "A narrow name is easier to refer", supportingText: "People can't recommend what they can't describe." },
      { role: "body", headline: "Niching down didn't shrink the business — it grew it", supportingText: "Referrals tripled within two quarters of the switch." },
      { role: "cta", headline: "Save this before you rewrite your own bio", supportingText: "" },
    ],
  },
  // 29 — tutorial
  {
    title: "How to Turn One Project Into a Case Study",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "save",
    funnelStage: "bofu",
    topicTag: "Case Studies",
    segment: "Framework Breakdown",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard layout resembling a case study outline, each step boxed like a document section.",
    slides: [
      { role: "hook", headline: "How to turn one project into a case study", supportingText: "The template behind every case study I publish." },
      { role: "body", headline: "Step 1: capture the baseline before you start", supportingText: "No before number means no credible after number." },
      { role: "body", headline: "Step 2: ask permission to publish on day one", supportingText: "Asking after the win is always a harder conversation." },
      { role: "body", headline: "Step 3: document 3 specific decisions, not the whole project", supportingText: "Specific beats comprehensive for a reader's attention." },
      { role: "body", headline: "Step 4: get one direct quote from the client", supportingText: "Their words sell harder than mine ever will." },
      { role: "body", headline: "Step 5: lead with the number, not the narrative", supportingText: "The result earns the right to tell the story." },
      { role: "body", headline: "Step 6: publish it within 2 weeks of the win", supportingText: "Momentum fades fast if you wait for 'perfect.'" },
      { role: "cta", headline: "Save this for your next project wrap-up", supportingText: "" },
    ],
  },
  // 30 — quote_chain
  {
    title: "Pricing Lessons I Learned the Expensive Way",
    pillar: "authority",
    contentType: "authority",
    archetype: "quote_chain",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Pricing Mindset",
    segment: "Quote Chain",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Rich burgundy-to-black gradient, oversized serif statement per slide, generous margins.",
    slides: [
      { role: "hook", headline: "Pricing lessons I learned the expensive way", supportingText: "" },
      { role: "body", headline: "A low price doesn't win trust. It erodes it.", supportingText: "" },
      { role: "body", headline: "Discounting fixes hesitation for about a week", supportingText: "" },
      { role: "body", headline: "Your rate is a decision, not a feeling", supportingText: "" },
      { role: "body", headline: "The client who negotiates hardest rarely pays easiest", supportingText: "" },
      { role: "body", headline: "Charge for the outcome, not the hours it took", supportingText: "" },
      { role: "cta", headline: "Save this for the next time you undercharge", supportingText: "" },
    ],
  },
  // 31 — quote_chain
  {
    title: "From Burnout to Boundaries",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "quote_chain",
    ctaType: "follow",
    funnelStage: "mofu",
    topicTag: "Founder Mindset",
    segment: "Quote Chain",
    backgroundStyle: "photo",
    backgroundCategory: "window_light",
    designNotes: "Soft window-light photo background, silhouette framing, one calm statement per slide.",
    slides: [
      { role: "hook", headline: "From burnout to boundaries", supportingText: "" },
      { role: "body", headline: "I used to answer client messages at 11pm", supportingText: "A badge of honor I wore too long." },
      { role: "body", headline: "Availability isn't the same thing as value", supportingText: "" },
      { role: "body", headline: "A boundary I set lost me exactly zero good clients", supportingText: "" },
      { role: "body", headline: "The clients worth keeping respected it immediately", supportingText: "" },
      { role: "body", headline: "Rested, I do better work in fewer hours", supportingText: "" },
      { role: "cta", headline: "Follow for more of the real side of building this", supportingText: "" },
    ],
  },
  // 32 — comparison
  {
    title: "In-House Market Entry Lead vs External Agency",
    pillar: "authority",
    contentType: "educational",
    archetype: "comparison",
    ctaType: "comment",
    funnelStage: "mofu",
    topicTag: "Hiring Decisions",
    segment: "",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Two-tone solid background, muted blue for In-House, deep orange for Agency.",
    slides: [
      { role: "hook", headline: "In-house hire vs external agency for expansion", supportingText: "Which one actually fits your stage?" },
      { role: "body", headline: "In-house: deep context, slower to ramp", supportingText: "They live your product but learn the new market from zero." },
      { role: "body", headline: "In-house costs compound even between launches", supportingText: "Salary runs whether or not a market is actively opening." },
      { role: "body", headline: "Agency: instant market expertise, less internal context", supportingText: "They know the market but not your product's edge cases." },
      { role: "body", headline: "Agency cost scales with the project, not the calendar", supportingText: "You pay for the push, not the pause between pushes." },
      { role: "body", headline: "Best fit: agency for entry, in-house for scale", supportingText: "I've seen this combo outperform either option alone." },
      { role: "cta", headline: "Comment IN-HOUSE or AGENCY — which fits you", supportingText: "" },
    ],
  },
  // 33 — before_after
  {
    title: "0 to 30+ Clients: The Real Numbers",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "before_after",
    ctaType: "link",
    funnelStage: "bofu",
    topicTag: "Founder Journey",
    segment: "Before/After",
    backgroundStyle: "screenshot",
    backgroundCategory: "",
    designNotes: "Mock dashboard/growth-chart screenshot background, bold stat callouts overlaid in white.",
    slides: [
      { role: "hook", headline: "0 to 30+ clients — the real numbers", supportingText: "Not the highlight reel. The actual math." },
      { role: "body", headline: "Year 1: 4 clients, 1 industry, ₹8K average project", supportingText: "Slow, scrappy, mostly cold outreach." },
      { role: "body", headline: "Year 1 income barely covered rent some months", supportingText: "The hardest 12 months of the whole build." },
      { role: "body", headline: "Year 2: 11 clients, 5 industries, first retainer signed", supportingText: "The month cash flow finally stopped being terrifying." },
      { role: "body", headline: "Year 3: 30+ clients, 15 industries, 6 countries", supportingText: "The number that still doesn't feel real some days." },
      { role: "body", headline: "Average project value grew over 10x in that span", supportingText: "Same hours in the day, completely different pricing." },
      { role: "cta", headline: "Link in bio to start your own engagement", supportingText: "" },
    ],
  },
  // 34 — quote_chain
  {
    title: "Confidence Isn't a Prerequisite — It's a Byproduct",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "quote_chain",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Founder Mindset",
    segment: "Quote Chain",
    backgroundStyle: "minimalist",
    backgroundCategory: "",
    designNotes: "Minimalist off-white background, single centered line per slide, slow typographic rhythm.",
    slides: [
      { role: "hook", headline: "Confidence isn't a prerequisite. It's a byproduct.", supportingText: "" },
      { role: "body", headline: "I didn't feel ready for my first client", supportingText: "" },
      { role: "body", headline: "I didn't feel ready for client 10, or 20, either", supportingText: "" },
      { role: "body", headline: "Readiness is built by the work, not waiting", supportingText: "" },
      { role: "body", headline: "Every version of me that waited stayed exactly the same", supportingText: "" },
      { role: "body", headline: "The version that started badly is here now", supportingText: "" },
      { role: "cta", headline: "Save this for the next time you feel unready", supportingText: "" },
    ],
  },
];
