// 33-carousel second batch -- Instagram carousel (multi-slide swipe post)
// content, parallel to the script library. Same creator persona as the
// 1000+ scripts in this repo: a young market-entry consultant who started
// around 18-19 after failing entrance exams, now runs a practice with
// 30+ clients across 15 industries and 6 countries.
//
// Distribution (33 total):
//   Archetype: listicle x5, myth_bust x4, tutorial x4, story_arc x4,
//   comparison x4, before_after x4, single_concept x4, quote_chain x4.
//   Funnel: tofu 18 / mofu 10 / bofu 5 (~54/30/15).
//   CTA: save 19, follow 5, comment 4, share 3, link 2 -- weighted to save.
//   Pillar: authority 25 / journey 8 (~76/24).
//   Background: solid 9, gradient 6, photo 6, whiteboard 4, screenshot 4,
//   minimalist 4.

import type { CarouselSeed } from "./carouselTypes";

export const CAROUSEL_BATCH_2_TAG = "carousel_batch_2_v1";

export const CAROUSEL_BATCH_2: CarouselSeed[] = [
  // 1
  {
    title: "3 Market-Entry Myths That Cost Founders Their First 6 Months",
    pillar: "authority",
    contentType: "educational",
    archetype: "myth_bust",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Market Entry Strategy",
    segment: "Myth Bust",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Deep navy-to-charcoal gradient, bold white headline type, small red strike-through icon on each myth slide.",
    slides: [
      { role: "hook", headline: "Everyone believes these market-entry myths", supportingText: "I've unwound all of them with real clients." },
      { role: "body", headline: "Myth: more capital means faster entry", supportingText: "Truth: capital without local trust buys you nothing." },
      { role: "body", headline: "Myth: the biggest market is the best first one", supportingText: "Truth: the easiest regulatory path wins early, not the biggest TAM." },
      { role: "body", headline: "Myth: you need an office before a partner", supportingText: "Truth: partner first, sign a lease 8-12 months later." },
      { role: "body", headline: "Myth: translating your site is localizing it", supportingText: "Truth: localization rebuilds the offer, pricing, and proof." },
      { role: "body", headline: "Myth: one entry plan fits every country", supportingText: "I've run 30+ entries, never reused a plan whole." },
      { role: "body", headline: "Myth: fast beats compliant", supportingText: "Truth: one skipped filing can freeze a launch for 90 days." },
      { role: "cta", headline: "Save this before you pick your next market", supportingText: "You'll want it back before the kickoff call." },
    ],
  },
  // 2
  {
    title: "5 Negotiation Levers I Pull Before I Ever Quote a Price",
    pillar: "authority",
    contentType: "educational",
    archetype: "listicle",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Deal Negotiation",
    segment: "Framework Breakdown",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Flat deep green background, large numbered badges top-left, condensed bold sans headline.",
    slides: [
      { role: "hook", headline: "5 negotiation levers before I quote a price", supportingText: "Save this -- you'll use it before your next call." },
      { role: "body", headline: "1. Set the anchor before they do", supportingText: "Whoever names the first number controls the frame." },
      { role: "body", headline: "2. Ask what their last provider cost", supportingText: "It tells you their real budget, not their stated one." },
      { role: "body", headline: "3. Trade scope, never trade rate", supportingText: "A discount sets a precedent. A smaller scope doesn't." },
      { role: "body", headline: "4. Go quiet after the number", supportingText: "The first person to speak after a price usually concedes." },
      { role: "body", headline: "5. Walk the deal before you need to", supportingText: "Clients negotiate harder with consultants who need the yes." },
      { role: "cta", headline: "Save this for your next client call", supportingText: "" },
    ],
  },
  // 3
  {
    title: "How I Write a Market-Entry Proposal That Closes in One Call",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Proposal Writing",
    segment: "Step-by-Step",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard texture background, marker-style handwriting font for step numbers, black ink headlines.",
    slides: [
      { role: "hook", headline: "How I write proposals that close in one call", supportingText: "6 steps, no generic templates." },
      { role: "body", headline: "Step 1: open with their numbers, not mine", supportingText: "First page quotes their market size back to them." },
      { role: "body", headline: "Step 2: name the risk they haven't said aloud", supportingText: "This is what makes them trust the rest of the doc." },
      { role: "body", headline: "Step 3: show the exact 90-day roadmap", supportingText: "Dates, not phases -- founders buy certainty." },
      { role: "body", headline: "Step 4: price in three tiers, not one", supportingText: "The middle tier is the one I actually want them to pick." },
      { role: "body", headline: "Step 5: cut every line that isn't a decision", supportingText: "If a slide doesn't ask for a yes, it gets deleted." },
      { role: "body", headline: "Step 6: end with one next action, not five", supportingText: "One calendar link beats a page of options." },
      { role: "cta", headline: "Save this and build your next proposal from it", supportingText: "" },
    ],
  },
  // 4
  {
    title: "I Failed My Entrance Exams at 18 -- Here's What Happened Next",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Origin Story",
    segment: "Case Study",
    backgroundStyle: "photo",
    backgroundCategory: "window_light",
    designNotes: "Soft window-light photo, warm overlay with 45% scrim, serif headline font for an intimate, reflective tone.",
    slides: [
      { role: "hook", headline: "I failed my entrance exams at 18", supportingText: "It's the best thing that ever happened to my career." },
      { role: "body", headline: "Everyone around me had a plan. I had none.", supportingText: "I spent that summer just answering messages for people." },
      { role: "body", headline: "A relative's friend needed help entering a new city", supportingText: "I said yes before I knew what I was agreeing to." },
      { role: "body", headline: "I had no framework, no case studies, no office", supportingText: "Just a notebook full of questions I asked everyone I could find." },
      { role: "body", headline: "That first project paid less than a part-time job", supportingText: "But it became the first case study I ever pitched." },
      { role: "body", headline: "Client two came from client one's referral", supportingText: "I never ran a single cold outreach campaign that year." },
      { role: "body", headline: "Today: 30+ clients, 15 industries, 6 countries", supportingText: "None of it needed the exam score I was so afraid of missing." },
      { role: "cta", headline: "Follow for more of how this actually built", supportingText: "" },
    ],
  },
  // 5
  {
    title: "Retainer vs Project Pricing -- Which One Actually Protects You",
    pillar: "authority",
    contentType: "educational",
    archetype: "comparison",
    ctaType: "comment",
    funnelStage: "mofu",
    topicTag: "Pricing Structure",
    segment: "Framework Breakdown",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Split-screen solid background, left panel muted blue, right panel muted amber, centered divider line.",
    slides: [
      { role: "hook", headline: "Retainer vs project -- which protects you?", supportingText: "I run both, for different reasons." },
      { role: "body", headline: "Retainer: predictable income, slower growth", supportingText: "Great for cash flow, capped on how fast you can scale it." },
      { role: "body", headline: "Retainer risk: scope quietly expands", supportingText: "Clients stretch a monthly fee until it covers everything." },
      { role: "body", headline: "Project: higher ceiling, harder forecasting", supportingText: "You eat the gap between projects if the pipeline dries up." },
      { role: "body", headline: "Project risk: every deal is a cold restart", supportingText: "No baseline trust carried over from the last engagement." },
      { role: "body", headline: "My split: 60% retainer, 40% project", supportingText: "Retainers fund the team, projects fund the growth." },
      { role: "cta", headline: "Comment A or B -- which one are you running", supportingText: "" },
    ],
  },
  // 6
  {
    title: "From Scope Creep Chaos to a Contract That Enforces Itself",
    pillar: "authority",
    contentType: "educational",
    archetype: "before_after",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Scope Management",
    segment: "Before / After",
    backgroundStyle: "screenshot",
    backgroundCategory: "",
    designNotes: "Mocked chat-thread screenshot style on slides showing the before, clean contract-clause mockup on the after slides.",
    slides: [
      { role: "hook", headline: "Scope creep chaos to self-enforcing contracts", supportingText: "It took one bad client to force the rebuild." },
      { role: "body", headline: "Before: scope lived in email threads", supportingText: "Every 'quick ask' had no paper trail to point back to." },
      { role: "body", headline: "Before: I billed extra work after the fact", supportingText: "Clients disputed invoices they never saw coming." },
      { role: "body", headline: "The turning point: a 40-hour unpaid scope creep", supportingText: "One client, one project, one lesson I never repeated." },
      { role: "body", headline: "After: every deliverable gets a line-item clause", supportingText: "If it's not listed, it's a new quote, not a favor." },
      { role: "body", headline: "After: change requests trigger an automatic re-quote", supportingText: "No more awkward conversations about 'extra' work." },
      { role: "body", headline: "Result: 0 scope disputes across the last 20 clients", supportingText: "The contract does the enforcing, not me." },
      { role: "cta", headline: "Save this before you send your next contract", supportingText: "" },
    ],
  },
  // 7
  {
    title: "Clients Don't Buy Expertise. They Buy Certainty.",
    pillar: "authority",
    contentType: "educational",
    archetype: "single_concept",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Client Psychology",
    segment: "",
    backgroundStyle: "minimalist",
    backgroundCategory: "",
    designNotes: "Pure white minimalist background, single oversized black serif statement per slide, generous negative space.",
    slides: [
      { role: "hook", headline: "Clients don't buy expertise. They buy certainty.", supportingText: "" },
      { role: "body", headline: "They already suspect they're right", supportingText: "Your credentials just confirm what they already feared." },
      { role: "body", headline: "They're paying to not be the one who's wrong", supportingText: "Every proposal is really a liability transfer." },
      { role: "body", headline: "That's why timelines matter more than jargon", supportingText: "A date they can repeat to their board beats a framework." },
      { role: "body", headline: "That's why case studies outsell credentials", supportingText: "Proof someone else survived the decision they're making." },
      { role: "body", headline: "Certainty is the actual product", supportingText: "The research, the plan, the deck -- all delivery mechanisms." },
      { role: "cta", headline: "Save this before you write your next pitch", supportingText: "" },
    ],
  },
  // 8
  {
    title: "What 30 Rejected Pitches Taught Me About Resilience",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "quote_chain",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Founder Mindset",
    segment: "",
    backgroundStyle: "photo",
    backgroundCategory: "walking_commute",
    designNotes: "Walking POV photo, high contrast black overlay at 55%, oversized centered quote-style type, one line per slide.",
    slides: [
      { role: "hook", headline: "30 rejections taught me more than one win did", supportingText: "" },
      { role: "body", headline: "Rejection 1-10: I thought my pitch was wrong", supportingText: "" },
      { role: "body", headline: "Rejection 11-20: I realized my timing was wrong", supportingText: "" },
      { role: "body", headline: "Rejection 21-25: I realized the client was wrong", supportingText: "" },
      { role: "body", headline: "Rejection 26-30: I stopped counting", supportingText: "" },
      { role: "body", headline: "The 31st pitch became my biggest client to date", supportingText: "" },
      { role: "body", headline: "Discipline outlasts motivation every time", supportingText: "" },
      { role: "cta", headline: "Save this for the next pitch you lose", supportingText: "" },
    ],
  },
  // 9
  {
    title: "5 Client Red Flags I Walk Away From Now",
    pillar: "authority",
    contentType: "educational",
    archetype: "listicle",
    ctaType: "share",
    funnelStage: "tofu",
    topicTag: "Client Screening",
    segment: "Framework Breakdown",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Deep maroon solid background, bold white numerals, thin warning-triangle icon beside each item.",
    slides: [
      { role: "hook", headline: "5 client red flags I walk away from now", supportingText: "Learned every one of these the expensive way." },
      { role: "body", headline: "1. \"We'll figure out scope as we go\"", supportingText: "Translation: unlimited asks, fixed fee." },
      { role: "body", headline: "2. They've fired their last 3 consultants", supportingText: "The pattern is rarely the consultants." },
      { role: "body", headline: "3. They want a call before the contract, every time", supportingText: "A stall tactic dressed up as diligence." },
      { role: "body", headline: "4. They negotiate the fee before they've seen the plan", supportingText: "They're optimizing for cheap, not for outcome." },
      { role: "body", headline: "5. No one internally owns the decision", supportingText: "You'll re-pitch the same deck to five people." },
      { role: "cta", headline: "Send this to someone vetting a new client", supportingText: "" },
    ],
  },
  // 10
  {
    title: "The Truth About Picking Your Niche in Consulting",
    pillar: "authority",
    contentType: "educational",
    archetype: "myth_bust",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Niche Selection",
    segment: "Myth Bust",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Warm orange-to-coral gradient, editorial serif headline, thin underline accent on the myth word.",
    slides: [
      { role: "hook", headline: "What everyone gets wrong about niching down", supportingText: "" },
      { role: "body", headline: "Myth: a narrow niche limits your revenue", supportingText: "Truth: it limits your competition, not your ceiling." },
      { role: "body", headline: "Myth: you have to pick one forever", supportingText: "Truth: I shifted niches twice in 4 years, on purpose." },
      { role: "body", headline: "Myth: broader positioning wins more pitches", supportingText: "Truth: I win fewer pitches now, at 3x the close rate." },
      { role: "body", headline: "Myth: niching means saying no to easy money", supportingText: "Truth: it means saying no to the wrong easy money." },
      { role: "body", headline: "Myth: industry expertise matters more than pattern recognition", supportingText: "Truth: I've entered markets in industries I'd never touched." },
      { role: "cta", headline: "Save this before your next repositioning", supportingText: "" },
    ],
  },
  // 11
  {
    title: "The 7-Step Due Diligence Framework I Run Before Any New Market",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Country Due Diligence",
    segment: "Framework Breakdown",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard background with a hand-drawn checklist aesthetic, numbered boxes ticked off slide by slide.",
    slides: [
      { role: "hook", headline: "The 7-step framework before any new market", supportingText: "Same checklist, every one of 6 countries." },
      { role: "body", headline: "Step 1: regulatory entry cost, not just tax rate", supportingText: "Registration timelines kill more launches than taxes do." },
      { role: "body", headline: "Step 2: local payment infrastructure check", supportingText: "If customers can't pay easily, nothing else matters." },
      { role: "body", headline: "Step 3: competitor pricing, in local currency", supportingText: "A converted price tells you nothing about perceived value." },
      { role: "body", headline: "Step 4: hiring cost and contract norms", supportingText: "Severance rules alone can double your real headcount cost." },
      { role: "body", headline: "Step 5: distribution partner landscape", supportingText: "Map who already owns the customer relationship." },
      { role: "body", headline: "Step 6: cultural objections to the category", supportingText: "The product rarely fails -- the framing usually does." },
      { role: "body", headline: "Step 7: a 90-day exit trigger, set in advance", supportingText: "Decide the failure line before you're emotionally in it." },
      { role: "cta", headline: "Save this and run it before your next launch", supportingText: "" },
    ],
  },
  // 12
  {
    title: "My First International Client Almost Didn't Happen",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Origin Story",
    segment: "Case Study",
    backgroundStyle: "photo",
    backgroundCategory: "coffee_shop",
    designNotes: "Warm coffee-shop photo with 50% scrim, cursive accent for the hook word, clean sans for body lines.",
    slides: [
      { role: "hook", headline: "My first international client almost fell through", supportingText: "A visa issue nearly ended it before it started." },
      { role: "body", headline: "I'd never worked across a border before", supportingText: "The client assumed I had -- I let them assume it." },
      { role: "body", headline: "Three days before kickoff, my documents got stuck", supportingText: "No consulate appointment for six weeks." },
      { role: "body", headline: "I ran the entire first phase remotely instead", supportingText: "Time zones meant 5am calls for a month straight." },
      { role: "body", headline: "The client never even noticed the scramble", supportingText: "The deliverables showed up on time, every time." },
      { role: "body", headline: "That project became my first real case study", supportingText: "It's still in every deck I send today." },
      { role: "body", headline: "I learned to build remote-first from day one", supportingText: "Every engagement since assumes I might not be in the room." },
      { role: "cta", headline: "Follow for more of how the early projects actually went", supportingText: "" },
    ],
  },
  // 13
  {
    title: "Hiring a Freelancer vs an Agency for Market Research",
    pillar: "authority",
    contentType: "educational",
    archetype: "comparison",
    ctaType: "comment",
    funnelStage: "mofu",
    topicTag: "Hiring Decisions",
    segment: "Framework Breakdown",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Split solid background, cool slate on one side, muted teal on the other, bold condensed headline font.",
    slides: [
      { role: "hook", headline: "Freelancer vs agency for market research", supportingText: "Both have a real place -- it depends on the stage." },
      { role: "body", headline: "Freelancer: cheaper, faster, one point of failure", supportingText: "Great under $5k budgets, risky past that." },
      { role: "body", headline: "Freelancer risk: no backup if they go dark", supportingText: "I've had to rescue two projects from this exact gap." },
      { role: "body", headline: "Agency: slower onboarding, built-in redundancy", supportingText: "You pay a premium for process you'll never see." },
      { role: "body", headline: "Agency risk: your account gets the junior team", supportingText: "The partner who pitched you rarely does the work." },
      { role: "body", headline: "My rule: freelancer for scoping, agency for scale", supportingText: "Validate cheap, then execute with redundancy." },
      { role: "cta", headline: "Comment A or B -- which one are you using right now", supportingText: "" },
    ],
  },
  // 14
  {
    title: "How We Cut Delivery Time From 14 Weeks to 6",
    pillar: "authority",
    contentType: "authority",
    archetype: "before_after",
    ctaType: "link",
    funnelStage: "bofu",
    topicTag: "Operations Overhaul",
    segment: "Case Study",
    backgroundStyle: "screenshot",
    backgroundCategory: "",
    designNotes: "Dashboard-style screenshot mockups contrasting the cluttered before timeline tracker with the clean after one.",
    slides: [
      { role: "hook", headline: "14 weeks to 6 -- what actually changed", supportingText: "The full breakdown of our ops rebuild." },
      { role: "body", headline: "Before: every client ran a custom process", supportingText: "No two engagements looked the same internally." },
      { role: "body", headline: "Before: research and strategy ran sequentially", supportingText: "Each phase waited on the last to fully close." },
      { role: "body", headline: "The fix: one standardized intake template", supportingText: "Every client answers the same 20 questions, week one." },
      { role: "body", headline: "The fix: research and strategy now run in parallel", supportingText: "Two workstreams, one shared deadline." },
      { role: "body", headline: "After: delivery dropped from 14 weeks to 6", supportingText: "Same depth of work, half the client wait." },
      { role: "body", headline: "After: client satisfaction scores rose with speed", supportingText: "Faster felt more rigorous, not less." },
      { role: "cta", headline: "Link in bio for the ops audit template we use", supportingText: "" },
    ],
  },
  // 15
  {
    title: "The Team I Didn't Think I Needed Until I Almost Broke",
    pillar: "authority",
    contentType: "educational",
    archetype: "single_concept",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Team Building",
    segment: "",
    backgroundStyle: "minimalist",
    backgroundCategory: "",
    designNotes: "Soft off-white minimalist background, single statement per slide in heavy grotesk, muted gray accent line.",
    slides: [
      { role: "hook", headline: "The team I didn't think I needed", supportingText: "Until I almost broke doing it all myself." },
      { role: "body", headline: "I ran 12 clients solo for two years", supportingText: "I told myself it was efficient. It wasn't." },
      { role: "body", headline: "I hired for tasks, not for trust", supportingText: "Trust is what actually lets you hand work off." },
      { role: "body", headline: "My first hire was a researcher, not an assistant", supportingText: "The bottleneck was thinking time, not admin time." },
      { role: "body", headline: "Delegation isn't losing control, it's buying range", supportingText: "I took on 3 new industries the year I hired." },
      { role: "body", headline: "A team that trusts you scales faster than you alone", supportingText: "" },
      { role: "cta", headline: "Save this before you hire your first person", supportingText: "" },
    ],
  },
  // 16
  {
    title: "What Discipline Looks Like When No One's Watching",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "quote_chain",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Founder Mindset",
    segment: "",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Muted charcoal-to-black gradient, large centered serif type, single line per slide, minimal ornamentation.",
    slides: [
      { role: "hook", headline: "Discipline is what happens when no one's watching", supportingText: "" },
      { role: "body", headline: "Motivation got me to the first client", supportingText: "" },
      { role: "body", headline: "Discipline got me through client five, ten, twenty", supportingText: "" },
      { role: "body", headline: "There were weeks I had zero new leads", supportingText: "" },
      { role: "body", headline: "I kept the same outreach rhythm anyway", supportingText: "" },
      { role: "body", headline: "The slow weeks built the system that caught the fast ones", supportingText: "" },
      { role: "cta", headline: "Save this for the week it feels slow", supportingText: "" },
    ],
  },
  // 17
  {
    title: "5 Contract Clauses I Will Never Send a Proposal Without",
    pillar: "authority",
    contentType: "educational",
    archetype: "listicle",
    ctaType: "save",
    funnelStage: "bofu",
    topicTag: "Contract Essentials",
    segment: "Framework Breakdown",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Deep forest-green solid background, legal-pad style numbered list typography, gold accent numerals.",
    slides: [
      { role: "hook", headline: "5 clauses every contract needs", supportingText: "No exceptions, regardless of client size." },
      { role: "body", headline: "1. A defined scope with named deliverables", supportingText: "Vague scope is the single biggest source of disputes." },
      { role: "body", headline: "2. A change-order clause with a re-quote trigger", supportingText: "New ask, new quote -- automatically, not awkwardly." },
      { role: "body", headline: "3. A kill fee for early termination", supportingText: "Protects the hours already sunk into a project." },
      { role: "body", headline: "4. An IP ownership clause, stated plainly", supportingText: "Who owns the frameworks after the engagement ends." },
      { role: "body", headline: "5. A payment schedule tied to milestones, not dates", supportingText: "Cash flow protection that also forces client momentum." },
      { role: "cta", headline: "Save this before you send your next contract", supportingText: "" },
    ],
  },
  // 18
  {
    title: "Local Partners: What Founders Keep Getting Wrong",
    pillar: "authority",
    contentType: "educational",
    archetype: "myth_bust",
    ctaType: "share",
    funnelStage: "tofu",
    topicTag: "Local Partnerships",
    segment: "Myth Bust",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Deep plum-to-navy gradient, bold sans headline, thin white rule dividing myth and truth lines.",
    slides: [
      { role: "hook", headline: "What founders get wrong about local partners", supportingText: "" },
      { role: "body", headline: "Myth: any local contact counts as a partner", supportingText: "Truth: a partner has skin in your specific outcome." },
      { role: "body", headline: "Myth: exclusivity protects you", supportingText: "Truth: exclusivity without performance clauses traps you." },
      { role: "body", headline: "Myth: more partners means more coverage", supportingText: "Truth: two confused partners cover less than one clear one." },
      { role: "body", headline: "Myth: equity partners try harder than paid ones", supportingText: "Truth: effort follows clarity of role, not ownership type." },
      { role: "body", headline: "Myth: you can skip due diligence on referrals", supportingText: "Truth: referred partners fail the same rate as cold ones." },
      { role: "cta", headline: "Send this to a founder vetting a local partner", supportingText: "" },
    ],
  },
  // 19
  {
    title: "The Cold Outreach Framework That Booked My First 10 Clients",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Cold Outreach",
    segment: "Step-by-Step",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard background, marker numbers, small arrow doodles connecting each step to the next.",
    slides: [
      { role: "hook", headline: "The outreach framework behind my first 10 clients", supportingText: "No ad spend, no agency, just this." },
      { role: "body", headline: "Step 1: find companies mid-expansion, not pre-expansion", supportingText: "A signal beats a guess every time." },
      { role: "body", headline: "Step 2: reference their specific expansion move", supportingText: "Generic outreach gets generic ignored." },
      { role: "body", headline: "Step 3: lead with a risk, not a service list", supportingText: "\"Here's what usually breaks at your stage\"." },
      { role: "body", headline: "Step 4: offer a 15-minute diagnostic, not a pitch", supportingText: "Lower the first ask, raise the second one." },
      { role: "body", headline: "Step 5: follow up on value, not on \"checking in\"", supportingText: "Each touch adds something new, never just a nudge." },
      { role: "body", headline: "Step 6: track reply rate by message variant", supportingText: "My first script converted at 4%. The fifth hit 19%." },
      { role: "cta", headline: "Save this and run it on your next 20 sends", supportingText: "" },
    ],
  },
  // 20
  {
    title: "Standing in a City I'd Never Visited, Pitching a Client I'd Never Met",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Origin Story",
    segment: "Case Study",
    backgroundStyle: "photo",
    backgroundCategory: "skyline",
    designNotes: "City skyline photo with blue-hour tone, 45% dark overlay, bold white condensed headline type.",
    slides: [
      { role: "hook", headline: "Pitching a client in a city I'd never visited", supportingText: "I landed four hours before the meeting." },
      { role: "body", headline: "I'd built the whole proposal from public data", supportingText: "No local contact, no prior visit, no safety net." },
      { role: "body", headline: "Halfway through, they asked about a competitor I'd missed", supportingText: "I didn't bluff -- I said I'd have the answer by morning." },
      { role: "body", headline: "I spent that night rebuilding the competitive section", supportingText: "Four hours of sleep, one new slide, no excuses." },
      { role: "body", headline: "I sent it before their office opened", supportingText: "They signed by lunch." },
      { role: "body", headline: "That client became a 6-country relationship", supportingText: "One honest night turned into years of work." },
      { role: "body", headline: "I'll never bluff a gap in the room again", supportingText: "Admitting it fast earns more trust than faking it." },
      { role: "cta", headline: "Follow for more stories from the early expansion years", supportingText: "" },
    ],
  },
  // 21
  {
    title: "Exclusive vs Non-Exclusive Partner Agreements",
    pillar: "authority",
    contentType: "educational",
    archetype: "comparison",
    ctaType: "comment",
    funnelStage: "mofu",
    topicTag: "Local Partnerships",
    segment: "Framework Breakdown",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Split solid background, deep navy vs warm rust, bold condensed headline font, thin center divider.",
    slides: [
      { role: "hook", headline: "Exclusive vs non-exclusive partner deals", supportingText: "The wrong choice can cost you a whole market." },
      { role: "body", headline: "Exclusive: deeper commitment, concentrated risk", supportingText: "One underperformer and the whole market stalls." },
      { role: "body", headline: "Exclusive risk: you can't course-correct mid-term", supportingText: "You're locked in while the data proves you wrong." },
      { role: "body", headline: "Non-exclusive: faster coverage, diluted priority", supportingText: "No single partner fights hard for your account." },
      { role: "body", headline: "Non-exclusive risk: partners compete on your own leads", supportingText: "Confusion in-market reads as a weak brand." },
      { role: "body", headline: "My rule: exclusive only after a 90-day pilot", supportingText: "Earn the lock-in, don't grant it on day one." },
      { role: "cta", headline: "Comment A or B -- which structure are you running", supportingText: "" },
    ],
  },
  // 22
  {
    title: "From Dreading Every Call to Firing the Client Myself",
    pillar: "authority",
    contentType: "educational",
    archetype: "before_after",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Client Offboarding",
    segment: "Before / After",
    backgroundStyle: "screenshot",
    backgroundCategory: "",
    designNotes: "Mock calendar-app screenshot showing dreaded recurring calls on the before slides, clean inbox on the after.",
    slides: [
      { role: "hook", headline: "Dreading every call to firing the client myself", supportingText: "Took me a year too long to make the move." },
      { role: "body", headline: "Before: every weekly call ran 90 minutes over", supportingText: "Scope kept expanding, invoices kept shrinking." },
      { role: "body", headline: "Before: I rationalized it as 'just a hard client'", supportingText: "Hard clients don't usually cost you your sleep." },
      { role: "body", headline: "The turning point: a Sunday night of dread", supportingText: "I realized I was afraid of a Monday call." },
      { role: "body", headline: "After: I sent a calm, specific offboarding email", supportingText: "No drama, just a 30-day transition plan." },
      { role: "body", headline: "After: I replaced the revenue in 6 weeks", supportingText: "With two clients who respected the scope I set." },
      { role: "body", headline: "The lesson: a bad client is a cost, not a client", supportingText: "" },
      { role: "cta", headline: "Save this for the client you've been avoiding", supportingText: "" },
    ],
  },
  // 23
  {
    title: "Scaling Without Burning Out: The One Rule I Don't Break",
    pillar: "authority",
    contentType: "educational",
    archetype: "single_concept",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Founder Burnout",
    segment: "",
    backgroundStyle: "minimalist",
    backgroundCategory: "",
    designNotes: "Pale sage minimalist background, single centered statement per slide, generous whitespace, light sans type.",
    slides: [
      { role: "hook", headline: "The one rule that kept me from burning out", supportingText: "" },
      { role: "body", headline: "I used to measure growth by client count", supportingText: "More clients felt like proof I was winning." },
      { role: "body", headline: "At 18 active clients, I stopped sleeping properly", supportingText: "Growth had quietly become the problem." },
      { role: "body", headline: "I set a hard cap: no more than 12 active at once", supportingText: "Revenue per client had to rise instead." },
      { role: "body", headline: "Fewer clients, higher retainers, better delivery", supportingText: "My margins improved the month I capped volume." },
      { role: "body", headline: "Capacity isn't a weakness, it's a pricing strategy", supportingText: "" },
      { role: "cta", headline: "Save this before you say yes to client 13", supportingText: "" },
    ],
  },
  // 24
  {
    title: "What Clients Are Actually Paying For",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "quote_chain",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Client Psychology",
    segment: "",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Soft gradient from slate to deep blue, large centered serif statements, one line per slide, no icons.",
    slides: [
      { role: "hook", headline: "What clients are actually paying for", supportingText: "After 30+ clients, it's rarely the deck." },
      { role: "body", headline: "They're not paying for the framework", supportingText: "" },
      { role: "body", headline: "They're paying for someone to own the decision", supportingText: "" },
      { role: "body", headline: "They're paying for a second opinion they can trust", supportingText: "" },
      { role: "body", headline: "They're paying for a timeline they can defend upward", supportingText: "" },
      { role: "body", headline: "They're paying to move faster than they would alone", supportingText: "" },
      { role: "cta", headline: "Save this before you write your next pitch deck", supportingText: "" },
    ],
  },
  // 25
  {
    title: "7 Questions to Answer Before You Enter a New Market",
    pillar: "authority",
    contentType: "educational",
    archetype: "listicle",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Market Entry Strategy",
    segment: "Framework Breakdown",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Flat deep indigo background, bold white numerals, consistent icon-free minimal list layout.",
    slides: [
      { role: "hook", headline: "7 questions before you enter a new market", supportingText: "Ask these before the flight, not after." },
      { role: "body", headline: "1. Who already owns this customer's trust?", supportingText: "" },
      { role: "body", headline: "2. What's the real cost to register and operate?", supportingText: "" },
      { role: "body", headline: "3. Can customers pay you in a way they already use?", supportingText: "" },
      { role: "body", headline: "4. What's the local price anchor for this category?", supportingText: "" },
      { role: "body", headline: "5. What objection kills the sale here specifically?", supportingText: "" },
      { role: "body", headline: "6. Who's your first local hire, and when?", supportingText: "" },
      { role: "body", headline: "7. What's your exit line if 90 days go badly?", supportingText: "" },
      { role: "cta", headline: "Save this before your next market-entry trip", supportingText: "" },
    ],
  },
  // 26
  {
    title: "Hiring Myths Killing Small Consultancies",
    pillar: "authority",
    contentType: "educational",
    archetype: "myth_bust",
    ctaType: "share",
    funnelStage: "tofu",
    topicTag: "Hiring Strategy",
    segment: "Myth Bust",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Burgundy-to-black gradient, bold white headline, hairline rule separating myth and truth per slide.",
    slides: [
      { role: "hook", headline: "Hiring myths killing small consultancies", supportingText: "" },
      { role: "body", headline: "Myth: hire generalists to stay flexible", supportingText: "Truth: specialists deliver faster, flexibility costs quality." },
      { role: "body", headline: "Myth: hire only when you're overwhelmed", supportingText: "Truth: by then you're hiring in panic, not in plan." },
      { role: "body", headline: "Myth: contractors are always cheaper than employees", supportingText: "Truth: turnover cost erases the hourly savings fast." },
      { role: "body", headline: "Myth: culture fit matters less in a small team", supportingText: "Truth: one bad fit damages a 4-person team more than a 40-person one." },
      { role: "body", headline: "Myth: your first hire should be an assistant", supportingText: "Truth: your first hire should remove your actual bottleneck." },
      { role: "cta", headline: "Send this to a founder about to make their first hire", supportingText: "" },
    ],
  },
  // 27
  {
    title: "A 5-Step Onboarding Process for Your First Hire",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Team Building",
    segment: "Step-by-Step",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard background, checklist-style numbered boxes, marker-font step labels.",
    slides: [
      { role: "hook", headline: "How to onboard your first hire in 5 steps", supportingText: "Skip this and you'll be retraining by month two." },
      { role: "body", headline: "Step 1: write the role before you post it", supportingText: "A vague job post attracts vague candidates." },
      { role: "body", headline: "Step 2: give them one real client file week one", supportingText: "Training on fake examples teaches nothing useful." },
      { role: "body", headline: "Step 3: pair every task with the 'why' behind it", supportingText: "Context builds judgment faster than instructions alone." },
      { role: "body", headline: "Step 4: schedule a 30-day scope check-in", supportingText: "Catch drift before it becomes a pattern." },
      { role: "body", headline: "Step 5: hand off one client relationship fully by day 60", supportingText: "Real ownership, not just task completion." },
      { role: "cta", headline: "Save this before your next onboarding week", supportingText: "" },
    ],
  },
  // 28
  {
    title: "The Week I Lost My Biggest Client",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "follow",
    funnelStage: "bofu",
    topicTag: "Client Retention",
    segment: "Case Study",
    backgroundStyle: "photo",
    backgroundCategory: "desk_laptop",
    designNotes: "Overhead desk-laptop photo, moody low-light tone, 50% scrim, bold condensed headline type.",
    slides: [
      { role: "hook", headline: "The week I lost my biggest client", supportingText: "40% of that quarter's revenue, gone in one email." },
      { role: "body", headline: "They cited 'strategic redirection', no warning before", supportingText: "I hadn't seen a single red flag coming." },
      { role: "body", headline: "I spent two days convinced I'd done something wrong", supportingText: "Replaying every call for a mistake that wasn't mine." },
      { role: "body", headline: "The real issue: I'd let one client become 40% of revenue", supportingText: "Concentration risk, not delivery failure." },
      { role: "body", headline: "I rebuilt the pipeline with a hard client-mix cap", supportingText: "No single account above 20% of revenue, ever again." },
      { role: "body", headline: "Three smaller clients replaced that one within the quarter", supportingText: "More stable, more resilient, more mine to control." },
      { role: "body", headline: "Diversification isn't caution, it's survival math", supportingText: "" },
      { role: "cta", headline: "Follow for more lessons from the harder weeks", supportingText: "" },
    ],
  },
  // 29
  {
    title: "Flat Fee vs Equity: Which Deal Structure Actually Pays Off",
    pillar: "authority",
    contentType: "educational",
    archetype: "comparison",
    ctaType: "comment",
    funnelStage: "bofu",
    topicTag: "Deal Structuring",
    segment: "Framework Breakdown",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Split solid background, muted gold vs deep slate, bold condensed type, center divider with a thin gold rule.",
    slides: [
      { role: "hook", headline: "Flat fee vs equity -- which deal pays off", supportingText: "I've taken both. Here's the honest math." },
      { role: "body", headline: "Flat fee: income now, no upside later", supportingText: "Predictable, but you never share in the win." },
      { role: "body", headline: "Flat fee risk: underpriced if the client scales fast", supportingText: "You did the hard early work for a fixed number." },
      { role: "body", headline: "Equity: no cash now, uncapped upside later", supportingText: "Most equity deals I've taken paid out zero." },
      { role: "body", headline: "Equity risk: you're unpaid for months of real work", supportingText: "Only take it if you can survive the zero case." },
      { role: "body", headline: "My rule: equity only on top of a reduced cash fee", supportingText: "Never full equity, never full risk." },
      { role: "cta", headline: "Comment A or B -- which deal structure do you run", supportingText: "" },
    ],
  },
  // 30
  {
    title: "How My Proposal Win Rate Went From 20% to 65%",
    pillar: "authority",
    contentType: "authority",
    archetype: "before_after",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Proposal Writing",
    segment: "Case Study",
    backgroundStyle: "screenshot",
    backgroundCategory: "",
    designNotes: "Mock proposal-doc screenshot comparison, cluttered dense before page vs clean structured after page.",
    slides: [
      { role: "hook", headline: "20% to 65% proposal win rate -- what changed", supportingText: "Same offer, completely different document." },
      { role: "body", headline: "Before: a 14-page proposal, generic cover page", supportingText: "Clients skimmed, then asked for a call to 'clarify'." },
      { role: "body", headline: "Before: pricing buried on page 11", supportingText: "By the time they got there, interest had cooled." },
      { role: "body", headline: "The fix: cut it to 5 pages, pricing on page 2", supportingText: "Respect their time, lead with the decision." },
      { role: "body", headline: "The fix: added a named risk section up front", supportingText: "Built trust before I'd even pitched the plan." },
      { role: "body", headline: "The fix: one clear CTA, one calendar link", supportingText: "No more proposals that ended in silence." },
      { role: "body", headline: "Result: win rate more than tripled in two quarters", supportingText: "" },
      { role: "cta", headline: "Save this before your next proposal goes out", supportingText: "" },
    ],
  },
  // 31
  {
    title: "Why Niching Down Actually Made Me More Money",
    pillar: "authority",
    contentType: "educational",
    archetype: "single_concept",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Niche Selection",
    segment: "",
    backgroundStyle: "minimalist",
    backgroundCategory: "",
    designNotes: "Warm cream minimalist background, single bold statement per slide, thin black rule underneath the headline.",
    slides: [
      { role: "hook", headline: "Niching down made me more money, not less", supportingText: "" },
      { role: "body", headline: "I used to pitch 'any founder, any market'", supportingText: "It made every pitch sound like every other one." },
      { role: "body", headline: "I narrowed to mid-size consumer brands entering Asia", supportingText: "Referrals started finding me instead of the reverse." },
      { role: "body", headline: "My fee per project rose 2.5x within a year", supportingText: "Specificity reads as expertise, not limitation." },
      { role: "body", headline: "I said no to more leads than I said yes to", supportingText: "Every no protected the credibility of every yes." },
      { role: "body", headline: "A narrow lane is easier to be known for", supportingText: "" },
      { role: "cta", headline: "Save this before you write your next bio", supportingText: "" },
    ],
  },
  // 32
  {
    title: "5 Lessons From 30+ Clients Across 6 Countries",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "quote_chain",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Reflections",
    segment: "",
    backgroundStyle: "photo",
    backgroundCategory: "bookshelf",
    designNotes: "Bookshelf reading-nook photo, soft focus, 45% warm overlay, serif centered statement per slide.",
    slides: [
      { role: "hook", headline: "5 lessons from 30+ clients, 6 countries", supportingText: "" },
      { role: "body", headline: "The plan survives first contact less often than you think", supportingText: "" },
      { role: "body", headline: "Trust travels faster than translated marketing ever does", supportingText: "" },
      { role: "body", headline: "The smallest client taught me the clearest lesson", supportingText: "" },
      { role: "body", headline: "Every market punishes the same mistake differently", supportingText: "" },
      { role: "body", headline: "The work gets easier. The decisions never do.", supportingText: "" },
      { role: "cta", headline: "Follow for more lessons from the next 30 clients", supportingText: "" },
    ],
  },
  // 33
  {
    title: "4 Signs You're Ready to Raise Your Prices",
    pillar: "authority",
    contentType: "educational",
    archetype: "listicle",
    ctaType: "link",
    funnelStage: "bofu",
    topicTag: "Pricing Strategy",
    segment: "Framework Breakdown",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Flat deep emerald background, bold white numerals, thin gold check-mark icon per confirmed sign.",
    slides: [
      { role: "hook", headline: "4 signs you're ready to raise your prices", supportingText: "If you hit 2 of these, it's overdue." },
      { role: "body", headline: "1. You're booked out more than 4 weeks ahead", supportingText: "Demand is already telling you the answer." },
      { role: "body", headline: "2. No prospect has pushed back on price in months", supportingText: "Zero friction means you're underpriced, not perfect." },
      { role: "body", headline: "3. Your scope has quietly grown since you last quoted", supportingText: "You're delivering more for the same old number." },
      { role: "body", headline: "4. You'd feel relief, not fear, turning a lead away", supportingText: "Relief means capacity, not desperation, is driving you." },
      { role: "cta", headline: "Link in bio for the pricing audit I use with clients", supportingText: "" },
    ],
  },
];
