// Batch 3 of carousel seed data (Instagram multi-slide swipe posts), a new
// parallel content type alongside the existing script library. Same founder
// persona as the 1000 existing scripts: started consulting around 18-19
// after failing entrance exams, runs a market-entry consulting practice,
// 30+ clients across 15 industries and 6 countries. This batch leans
// heavier into journey/story_arc and quote_chain carousels than the other
// two batches, to carry more of the personal/founder-story weight across
// the full 100-carousel set.

import type { CarouselSeed } from "./carouselTypes";

export const CAROUSEL_BATCH_3_TAG = "carousel_batch_3_v1";

export const CAROUSEL_BATCH_3: CarouselSeed[] = [
  // ---------- Listicle (4) ----------
  {
    title: "7 Questions I Ask Before I Take Any Client",
    pillar: "authority",
    contentType: "educational",
    archetype: "listicle",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Client Vetting",
    segment: "Framework",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Deep navy solid background, bold white numerals per slide, clean sans-serif headlines.",
    slides: [
      { role: "hook", headline: "7 questions I ask before I take any client", supportingText: "" },
      { role: "body", headline: "Q1: Why this market, why now?", supportingText: "Vague answers mean the project isn't ready." },
      { role: "body", headline: "Q2: What's your actual budget, not your wish list?", supportingText: "" },
      { role: "body", headline: "Q3: Who already failed at this before you?", supportingText: "" },
      { role: "body", headline: "Q4: What if this takes 18 months, not 6?", supportingText: "" },
      { role: "body", headline: "Q5: Is the decision-maker in this room?", supportingText: "" },
      { role: "body", headline: "Q6: What does success look like in numbers?", supportingText: "" },
      { role: "body", headline: "Q7: Can you survive a wrong first guess?", supportingText: "" },
      { role: "cta", headline: "Save this before your next client call", supportingText: "" },
    ],
  },
  {
    title: "6 Signs a Market Is Actually Ready for You",
    pillar: "authority",
    contentType: "educational",
    archetype: "listicle",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Market Readiness",
    segment: "Checklist",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Teal-to-navy gradient, bold white headlines, small checkmark icon per slide.",
    slides: [
      { role: "hook", headline: "6 signs a market is actually ready for you", supportingText: "" },
      { role: "body", headline: "Local competitors charge more than you'd guess", supportingText: "" },
      { role: "body", headline: "Customers are already improvising a workaround", supportingText: "" },
      { role: "body", headline: "Import or distribution channels already exist", supportingText: "" },
      { role: "body", headline: "Regulation hasn't closed the door, it's just slow", supportingText: "" },
      { role: "body", headline: "3+ strangers independently validate the pain", supportingText: "" },
      { role: "body", headline: "You can name your first 10 customers by type", supportingText: "" },
      { role: "cta", headline: "Save this before you scope your next expansion", supportingText: "" },
    ],
  },
  {
    title: "6 Numbers I Pull Before I Quote Any Client",
    pillar: "authority",
    contentType: "educational",
    archetype: "listicle",
    ctaType: "follow",
    funnelStage: "mofu",
    topicTag: "Pricing Research",
    segment: "Behind the Scenes",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard texture background, marker-style handwritten numerals, black ink headline font.",
    slides: [
      { role: "hook", headline: "6 numbers I pull before I quote a client", supportingText: "" },
      { role: "body", headline: "Market size, but the real addressable slice", supportingText: "" },
      { role: "body", headline: "Average deal size of 3 local competitors", supportingText: "" },
      { role: "body", headline: "Import duty or compliance cost, if relevant", supportingText: "" },
      { role: "body", headline: "Time-to-first-revenue for similar entries", supportingText: "" },
      { role: "body", headline: "Client's existing CAC in their home market", supportingText: "" },
      { role: "body", headline: "Number of comparable pilots that failed", supportingText: "" },
      { role: "body", headline: "My own hours, padded by 30%", supportingText: "" },
      { role: "cta", headline: "Follow for more of how I actually price projects", supportingText: "" },
    ],
  },
  {
    title: "5 Things I Wish I Knew at 19 Starting This",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "listicle",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Early Lessons",
    segment: "Founder Story",
    backgroundStyle: "photo",
    backgroundCategory: "walking_commute",
    designNotes: "Walking POV photo background with a 50% dark scrim, warm white headline text.",
    slides: [
      { role: "hook", headline: "5 things I wish I knew at 19 starting this", supportingText: "" },
      { role: "body", headline: "Nobody hires you for your age, they hire your questions", supportingText: "" },
      { role: "body", headline: "Your first client won't be your biggest, and that's fine", supportingText: "" },
      { role: "body", headline: "Charging too little doesn't buy you more trust", supportingText: "" },
      { role: "body", headline: "You'll be wrong about a market at least once a year", supportingText: "" },
      { role: "body", headline: "A notebook of questions beats a deck of slides", supportingText: "" },
      { role: "body", headline: "Saying no protects your reputation more than yes protects income", supportingText: "" },
      { role: "cta", headline: "Follow for more of what I wish I'd known earlier", supportingText: "" },
    ],
  },

  // ---------- Single Concept (4) ----------
  {
    title: "Market Entry Isn't a Launch. It's a Bet.",
    pillar: "authority",
    contentType: "educational",
    archetype: "single_concept",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Strategy Mindset",
    segment: "Reframe",
    backgroundStyle: "minimalist",
    backgroundCategory: "",
    designNotes: "Off-white minimalist background, large serif headline centered, generous negative space.",
    slides: [
      { role: "hook", headline: "Market entry isn't a launch. It's a bet.", supportingText: "" },
      { role: "body", headline: "A launch assumes you already know the market wants this", supportingText: "" },
      { role: "body", headline: "A bet assumes you're testing, not confirming", supportingText: "" },
      { role: "body", headline: "Bets have a size you're willing to lose", supportingText: "" },
      { role: "body", headline: "Most failed entries never set that size", supportingText: "" },
      { role: "body", headline: "They treated the first market like the only market", supportingText: "" },
      { role: "body", headline: "Size your bet before you size your ambition", supportingText: "" },
      { role: "cta", headline: "Save this before you plan your next market entry", supportingText: "" },
    ],
  },
  {
    title: "Your TAM Slide Is Lying to You",
    pillar: "authority",
    contentType: "educational",
    archetype: "single_concept",
    ctaType: "comment",
    funnelStage: "mofu",
    topicTag: "Market Sizing",
    segment: "Reality Check",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Charcoal solid background, oversized bold headline number treatment, red accent underline.",
    slides: [
      { role: "hook", headline: "Your TAM slide is lying to you", supportingText: "" },
      { role: "body", headline: "Total addressable market isn't total addressable revenue", supportingText: "" },
      { role: "body", headline: "Most of it can't afford you, won't switch, or can't be reached", supportingText: "" },
      { role: "body", headline: "I've seen a $2B TAM slide hide a $40M real opportunity", supportingText: "" },
      { role: "body", headline: "Investors have seen this slide a thousand times", supportingText: "" },
      { role: "body", headline: "They're testing if you know it's wrong, not impressed by it", supportingText: "" },
      { role: "body", headline: "Show the serviceable slice, not the headline number", supportingText: "" },
      { role: "cta", headline: "Comment TAM and I'll send how I actually size one", supportingText: "" },
    ],
  },
  {
    title: "The Pilot Market Is the Whole Strategy",
    pillar: "authority",
    contentType: "educational",
    archetype: "single_concept",
    ctaType: "link",
    funnelStage: "bofu",
    topicTag: "Pilot Strategy",
    segment: "Positioning",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Deep purple-to-navy gradient, bold centered headline, minimal supporting text below.",
    slides: [
      { role: "hook", headline: "The pilot market is the whole strategy", supportingText: "" },
      { role: "body", headline: "Most founders treat it as a formality before the 'real' plan", supportingText: "" },
      { role: "body", headline: "The pilot IS the plan, just running at a smaller size", supportingText: "" },
      { role: "body", headline: "Every assumption you're scared to test shows up here first", supportingText: "" },
      { role: "body", headline: "Skipping a real pilot costs more later, at scale", supportingText: "" },
      { role: "body", headline: "Design it like the whole business depends on it", supportingText: "" },
      { role: "cta", headline: "Link in bio to book a pilot-market strategy session", supportingText: "" },
    ],
  },
  {
    title: "Nobody Tells You Confidence Comes After, Not Before",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "single_concept",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Mindset",
    segment: "Mindset",
    backgroundStyle: "photo",
    backgroundCategory: "window_light",
    designNotes: "Soft side-lit window photo background, warm serif headline, calm aspirational mood.",
    slides: [
      { role: "hook", headline: "Nobody tells you confidence comes after, not before", supportingText: "" },
      { role: "body", headline: "I didn't feel ready before my first client meeting at 19", supportingText: "" },
      { role: "body", headline: "I don't fully feel ready before most meetings now either", supportingText: "" },
      { role: "body", headline: "What changed is how much evidence I have against the fear", supportingText: "" },
      { role: "body", headline: "30+ clients later, the evidence just got louder", supportingText: "" },
      { role: "body", headline: "Waiting to feel ready is waiting for a feeling that comes last", supportingText: "" },
      { role: "body", headline: "Start building the evidence, the confidence catches up", supportingText: "" },
      { role: "cta", headline: "Follow for more honest talk about building this", supportingText: "" },
    ],
  },

  // ---------- Before / After (4) ----------
  {
    title: "0 Clients in a New Market to a Repeatable Playbook in 90 Days",
    pillar: "authority",
    contentType: "educational",
    archetype: "before_after",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Market-Entry Playbook",
    segment: "Case Study",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Navy-to-teal gradient, week-range labels in a small badge per slide, bold white headlines.",
    slides: [
      { role: "hook", headline: "0 clients in a new market to a playbook in 90 days", supportingText: "" },
      { role: "body", headline: "Before: a founder with product, zero local traction", supportingText: "" },
      { role: "body", headline: "Week 1-2: mapped 3 possible entry segments, not 1", supportingText: "" },
      { role: "body", headline: "Week 3-6: ran a 12-customer pilot in the smallest one", supportingText: "" },
      { role: "body", headline: "Week 7-9: fixed pricing and onboarding from pilot feedback", supportingText: "" },
      { role: "body", headline: "Week 10-13: scaled the fixed version to 40 customers", supportingText: "" },
      { role: "body", headline: "After: a documented playbook their team could run alone", supportingText: "" },
      { role: "cta", headline: "Save this if you're planning a market entry this year", supportingText: "" },
    ],
  },
  {
    title: "Before: Guessing Pricing. After: No More Pushback.",
    pillar: "authority",
    contentType: "educational",
    archetype: "before_after",
    ctaType: "link",
    funnelStage: "bofu",
    topicTag: "Pricing Strategy",
    segment: "Case Study",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Forest green solid background, split-style before/after labels in small caps, clean sans-serif.",
    slides: [
      { role: "hook", headline: "Before: guessing pricing. After: no more pushback.", supportingText: "" },
      { role: "body", headline: "Before: pricing copied from home market, converted at exchange rate", supportingText: "" },
      { role: "body", headline: "Clients pushed back on almost every deal", supportingText: "" },
      { role: "body", headline: "We rebuilt pricing around local willingness-to-pay, not conversion math", supportingText: "" },
      { role: "body", headline: "Added a local-only entry tier for the first 90 days", supportingText: "" },
      { role: "body", headline: "Close rate went from 1 in 5 to 1 in 2", supportingText: "" },
      { role: "body", headline: "After: pricing that explains itself before the client asks", supportingText: "" },
      { role: "cta", headline: "Link in bio if you want your pricing rebuilt this way", supportingText: "" },
    ],
  },
  {
    title: "Before: Failed Every Entrance Exam. After: 30+ Clients, 6 Countries.",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "before_after",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Journey",
    segment: "Founder Story",
    backgroundStyle: "photo",
    backgroundCategory: "walking_commute",
    designNotes: "Walking commute photo background with dark scrim, bold white headline, momentum feel.",
    slides: [
      { role: "hook", headline: "Before: failed every entrance exam. After: 6 countries.", supportingText: "" },
      { role: "body", headline: "At 18, I didn't get into a single program I applied for", supportingText: "" },
      { role: "body", headline: "I spent the next year doing small research gigs nobody wanted", supportingText: "" },
      { role: "body", headline: "One gig became a client. That client became a referral", supportingText: "" },
      { role: "body", headline: "Six years later: 30+ clients, 15 industries, 6 countries", supportingText: "" },
      { role: "body", headline: "None of it followed the path anyone told me to take", supportingText: "" },
      { role: "body", headline: "The exams measured one thing. They weren't measuring this.", supportingText: "" },
      { role: "cta", headline: "Follow for more of how this actually happened", supportingText: "" },
    ],
  },
  {
    title: "Before: Chasing Every Client. After: Clients Chasing Me.",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "before_after",
    ctaType: "comment",
    funnelStage: "mofu",
    topicTag: "Client Acquisition",
    segment: "Lesson Learned",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Warm terracotta solid background, handwritten-style accent on key phrase, friendly tone.",
    slides: [
      { role: "hook", headline: "Before: chasing every client. After: clients chasing me.", supportingText: "" },
      { role: "body", headline: "First 2 years: cold outreach, every pitch, every maybe", supportingText: "" },
      { role: "body", headline: "Then I turned client work into visible case studies", supportingText: "" },
      { role: "body", headline: "Referrals started outpacing outreach within a year", supportingText: "" },
      { role: "body", headline: "Most new clients now open with \"I was told to call you\"", supportingText: "" },
      { role: "body", headline: "The shift wasn't luck, it was making the work visible", supportingText: "" },
      { role: "cta", headline: "Comment REFERRAL and I'll share how I made that shift", supportingText: "" },
    ],
  },

  // ---------- Myth Bust (4) ----------
  {
    title: "3 Market-Entry Myths That Cost Founders Real Money",
    pillar: "authority",
    contentType: "educational",
    archetype: "myth_bust",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Market-Entry Myths",
    segment: "Myth vs Truth",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Deep red solid background, \"Myth\" struck through in slide design, \"Truth\" in bold white.",
    slides: [
      { role: "hook", headline: "3 market-entry myths that cost founders real money", supportingText: "" },
      { role: "body", headline: "Myth: bigger market size means bigger opportunity", supportingText: "" },
      { role: "body", headline: "Truth: a reachable segment beats an unreachable giant", supportingText: "" },
      { role: "body", headline: "Myth: you need to be first to win", supportingText: "" },
      { role: "body", headline: "Truth: 3rd movers win by fixing what the first two got wrong", supportingText: "" },
      { role: "body", headline: "Myth: localizing is just translating the website", supportingText: "" },
      { role: "body", headline: "Truth: pricing and trust signals matter more than language", supportingText: "" },
      { role: "cta", headline: "Save this before you write your next entry plan", supportingText: "" },
    ],
  },
  {
    title: "Myth: Bigger Market Equals Better Opportunity",
    pillar: "authority",
    contentType: "educational",
    archetype: "myth_bust",
    ctaType: "share",
    funnelStage: "mofu",
    topicTag: "Market Sizing Myths",
    segment: "Myth vs Truth",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Amber-to-red gradient, bold contrarian headline, numbers called out in large type.",
    slides: [
      { role: "hook", headline: "Myth: bigger market equals better opportunity", supportingText: "" },
      { role: "body", headline: "A client chose a $4B market over a $300M one on size alone", supportingText: "" },
      { role: "body", headline: "The $4B market had 40 entrenched competitors", supportingText: "" },
      { role: "body", headline: "The $300M market had exactly 2, both underserving it badly", supportingText: "" },
      { role: "body", headline: "We picked the smaller market. They owned 18% in year one", supportingText: "" },
      { role: "body", headline: "Size tells you the ceiling, not the door", supportingText: "" },
      { role: "body", headline: "Check who's already inside before you check room size", supportingText: "" },
      { role: "cta", headline: "Send this to a founder chasing the biggest market, not the right one", supportingText: "" },
    ],
  },
  {
    title: "Myth: You Need a Local Partner on Day 1",
    pillar: "authority",
    contentType: "educational",
    archetype: "myth_bust",
    ctaType: "share",
    funnelStage: "tofu",
    topicTag: "Entry Strategy Myths",
    segment: "Myth vs Truth",
    backgroundStyle: "minimalist",
    backgroundCategory: "",
    designNotes: "Pale gray minimalist background, bold black sans-serif headline, single red accent word.",
    slides: [
      { role: "hook", headline: "Myth: you need a local partner on day 1", supportingText: "" },
      { role: "body", headline: "A partner too early often means giving up margin for comfort", supportingText: "" },
      { role: "body", headline: "A 60-day pilot can test most of what a partner offers, for free", supportingText: "" },
      { role: "body", headline: "I've seen partnerships signed before there was proof of demand", supportingText: "" },
      { role: "body", headline: "Earn partner leverage with early traction, not a pitch deck", supportingText: "" },
      { role: "body", headline: "Partner when you need scale, not when you need confidence", supportingText: "" },
      { role: "cta", headline: "Send this to someone about to sign a partnership too early", supportingText: "" },
    ],
  },
  {
    title: "Myth: Consultants Have It All Figured Out by 25",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "myth_bust",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Mindset",
    segment: "Myth vs Truth",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Soft dusty blue solid background, honest confessional tone, medium-weight sans-serif.",
    slides: [
      { role: "hook", headline: "Myth: consultants have it all figured out by 25", supportingText: "" },
      { role: "body", headline: "I still open some client calls with a knot in my stomach", supportingText: "" },
      { role: "body", headline: "I've second-guessed pricing decisions the night before sending them", supportingText: "" },
      { role: "body", headline: "What looks like certainty from outside is practiced doubt", supportingText: "" },
      { role: "body", headline: "30+ clients in, I've learned to act through the doubt", supportingText: "" },
      { role: "body", headline: "That's the actual skill nobody puts on a slide", supportingText: "" },
      { role: "body", headline: "Figured out and functional under uncertainty aren't the same", supportingText: "" },
      { role: "cta", headline: "Follow for the honest version of building this", supportingText: "" },
    ],
  },

  // ---------- Comparison (4) ----------
  {
    title: "Franchise Entry vs. Direct Entry: Which One Actually Wins",
    pillar: "authority",
    contentType: "educational",
    archetype: "comparison",
    ctaType: "comment",
    funnelStage: "mofu",
    topicTag: "Entry Models",
    segment: "Comparison",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Split-screen style solid background, left/right labels per option, bold centered VS divider.",
    slides: [
      { role: "hook", headline: "Franchise entry vs. direct entry — which wins?", supportingText: "" },
      { role: "body", headline: "Franchise: faster local presence, less control of execution", supportingText: "" },
      { role: "body", headline: "Direct: full control, you absorb every local mistake yourself", supportingText: "" },
      { role: "body", headline: "Franchise fits when brand consistency beats margin", supportingText: "" },
      { role: "body", headline: "Direct fits when the product needs local iteration to work", supportingText: "" },
      { role: "body", headline: "Direct wins more often in markets under 5 years old", supportingText: "" },
      { role: "body", headline: "Franchise wins once the playbook is proven and repeatable", supportingText: "" },
      { role: "cta", headline: "Comment FRANCHISE or DIRECT — which fits your expansion", supportingText: "" },
    ],
  },
  {
    title: "Hiring a Consultant vs. DIY Market Research",
    pillar: "authority",
    contentType: "educational",
    archetype: "comparison",
    ctaType: "link",
    funnelStage: "bofu",
    topicTag: "Build vs Buy",
    segment: "Comparison",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard texture, two-column marker-style comparison, black and blue ink contrast.",
    slides: [
      { role: "hook", headline: "Hiring a consultant vs. DIY market research", supportingText: "" },
      { role: "body", headline: "DIY: cheaper upfront, you learn the market on your own budget", supportingText: "" },
      { role: "body", headline: "Consultant: costs more upfront, usually skips 2-3 expensive mistakes", supportingText: "" },
      { role: "body", headline: "DIY works when timelines are loose and the market is familiar", supportingText: "" },
      { role: "body", headline: "A consultant earns their fee fastest in unfamiliar, fast-moving markets", supportingText: "" },
      { role: "body", headline: "The real cost of DIY is the 4 months lost redoing it", supportingText: "" },
      { role: "body", headline: "Pick based on how much that time is actually worth to you", supportingText: "" },
      { role: "cta", headline: "Link in bio to see if a consultant makes sense for your entry", supportingText: "" },
    ],
  },
  {
    title: "B2B Market Entry vs. B2C — Not the Same Playbook",
    pillar: "authority",
    contentType: "educational",
    archetype: "comparison",
    ctaType: "comment",
    funnelStage: "tofu",
    topicTag: "Entry Strategy",
    segment: "Comparison",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Blue-to-green gradient, bold B2B/B2C labels in contrasting colors, clean modern sans-serif.",
    slides: [
      { role: "hook", headline: "B2B market entry vs. B2C — not the same playbook", supportingText: "" },
      { role: "body", headline: "B2B: slower sales cycle, each client worth 10x more", supportingText: "" },
      { role: "body", headline: "B2C: faster feedback, but needs volume to survive a bad month", supportingText: "" },
      { role: "body", headline: "B2B entry lives or dies on 3-5 anchor relationships", supportingText: "" },
      { role: "body", headline: "B2C entry lives or dies on distribution and repeat purchase", supportingText: "" },
      { role: "body", headline: "Know which game you're actually playing before the plan", supportingText: "" },
      { role: "cta", headline: "Comment B2B or B2C — which are you entering this year", supportingText: "" },
    ],
  },
  {
    title: "Year 1 Me vs. Year 5 Me",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "comparison",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Growth",
    segment: "Then vs Now",
    backgroundStyle: "photo",
    backgroundCategory: "coffee_shop",
    designNotes: "Warm coffee-shop photo background, soft scrim, year labels as small badges per slide.",
    slides: [
      { role: "hook", headline: "Year 1 me vs. year 5 me, running this business", supportingText: "" },
      { role: "body", headline: "Year 1: said yes to every client who could pay", supportingText: "" },
      { role: "body", headline: "Year 5: say no to most clients who aren't the right fit", supportingText: "" },
      { role: "body", headline: "Year 1: built every proposal from scratch, every time", supportingText: "" },
      { role: "body", headline: "Year 5: have a system I can hand to someone else", supportingText: "" },
      { role: "body", headline: "Year 1: worked every hour to prove I belonged in the room", supportingText: "" },
      { role: "body", headline: "Year 5: work fewer hours, let the track record speak", supportingText: "" },
      { role: "cta", headline: "Follow to see where year 10 goes", supportingText: "" },
    ],
  },

  // ---------- Tutorial (4) ----------
  {
    title: "How to Pick Your First Entry Country in 7 Steps",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Country Selection",
    segment: "Mini Guide",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard texture background, numbered step badges, marker-style arrows connecting slides.",
    slides: [
      { role: "hook", headline: "How to pick your first entry country in 7 steps", supportingText: "" },
      { role: "body", headline: "Step 1: List every market where someone already asks for you", supportingText: "" },
      { role: "body", headline: "Step 2: Cut any market where you can't name 3 competitors", supportingText: "" },
      { role: "body", headline: "Step 3: Check regulatory time-to-launch, not just market size", supportingText: "" },
      { role: "body", headline: "Step 4: Score each market on payment and distribution access", supportingText: "" },
      { role: "body", headline: "Step 5: Talk to 10 real potential customers before deciding", supportingText: "" },
      { role: "body", headline: "Step 6: Pick the reachable market, not the impressive one", supportingText: "" },
      { role: "body", headline: "Step 7: Set a 90-day pilot budget you're willing to lose", supportingText: "" },
      { role: "cta", headline: "Save this for your next country selection decision", supportingText: "" },
    ],
  },
  {
    title: "How I Build Proposals Clients Actually Say Yes To",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Proposal Writing",
    segment: "Mini Guide",
    backgroundStyle: "whiteboard",
    backgroundCategory: "",
    designNotes: "Whiteboard texture, 9-step numbered sequence, consistent marker-style step badge top left.",
    slides: [
      { role: "hook", headline: "How I build proposals clients actually say yes to", supportingText: "" },
      { role: "body", headline: "Step 1: Open with their number, not your process", supportingText: "" },
      { role: "body", headline: "Step 2: Name the exact market risk they're worried about", supportingText: "" },
      { role: "body", headline: "Step 3: Show a comparable result, not a generic case study", supportingText: "" },
      { role: "body", headline: "Step 4: Break the project into phases, not one big ask", supportingText: "" },
      { role: "body", headline: "Step 5: Price phase one small enough to be a low-risk yes", supportingText: "" },
      { role: "body", headline: "Step 6: Attach a timeline with dates, not just durations", supportingText: "" },
      { role: "body", headline: "Step 7: Name what happens if they do nothing", supportingText: "" },
      { role: "body", headline: "Step 8: Put the next step on the same page as the price", supportingText: "" },
      { role: "body", headline: "Step 9: Send it within 48 hours, not a week later", supportingText: "" },
      { role: "cta", headline: "Save this before you send your next proposal", supportingText: "" },
    ],
  },
  {
    title: "How I Build a Client's Entry Timeline in 4 Steps",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "link",
    funnelStage: "bofu",
    topicTag: "Project Planning",
    segment: "Behind the Scenes",
    backgroundStyle: "screenshot",
    backgroundCategory: "",
    designNotes: "Mock project-planning tool screenshot background with a text panel overlay for legibility.",
    slides: [
      { role: "hook", headline: "How I build a client's entry timeline in 4 steps", supportingText: "" },
      { role: "body", headline: "Step 1: Work backward from cash runway, not the calendar", supportingText: "" },
      { role: "body", headline: "Step 2: Mark every regulatory or compliance checkpoint first", supportingText: "" },
      { role: "body", headline: "Step 3: Build a 2-week buffer after every external dependency", supportingText: "" },
      { role: "body", headline: "Step 4: Set one go/no-go decision point before full scale", supportingText: "" },
      { role: "body", headline: "This exact template runs on all 30+ of my projects", supportingText: "" },
      { role: "body", headline: "It's saved more launches by slowing them down than speeding up", supportingText: "" },
      { role: "body", headline: "Most timelines fail by planning for best case, not real case", supportingText: "" },
      { role: "cta", headline: "Link in bio for the timeline template I actually use", supportingText: "" },
    ],
  },
  {
    title: "How to Validate Demand Before You Spend a Rupee",
    pillar: "authority",
    contentType: "educational",
    archetype: "tutorial",
    ctaType: "save",
    funnelStage: "mofu",
    topicTag: "Demand Validation",
    segment: "Mini Guide",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Deep olive solid background, numbered step badges, bold white sans-serif headlines.",
    slides: [
      { role: "hook", headline: "How to validate demand before you spend a rupee", supportingText: "" },
      { role: "body", headline: "Step 1: Find where people are already improvising a fix", supportingText: "" },
      { role: "body", headline: "Step 2: Post a fake-door offer and track real clicks", supportingText: "" },
      { role: "body", headline: "Step 3: Call 15 people who clicked, not just the 2 who replied", supportingText: "" },
      { role: "body", headline: "Step 4: Ask what they use now, not what they'd want", supportingText: "" },
      { role: "body", headline: "Step 5: Get 5 people to pay before launch, even a deposit", supportingText: "" },
      { role: "body", headline: "If you can't get 5 yeses here, the market isn't ready yet", supportingText: "" },
      { role: "cta", headline: "Save this before you build anything for a new market", supportingText: "" },
    ],
  },

  // ---------- Story Arc (5) ----------
  {
    title: "I Failed Every Entrance Exam at 18. Here's What Happened Next.",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Journey",
    segment: "Founder Story",
    backgroundStyle: "photo",
    backgroundCategory: "walking_commute",
    designNotes: "Walking commute photo background with dark scrim, warm reflective tone, serif headline font.",
    slides: [
      { role: "hook", headline: "I failed every entrance exam at 18. Here's what happened next.", supportingText: "" },
      { role: "body", headline: "Every plan I'd made assumed I'd get in somewhere", supportingText: "" },
      { role: "body", headline: "None of the results came back the way I needed", supportingText: "" },
      { role: "body", headline: "I had no plan B, because I'd never needed one", supportingText: "" },
      { role: "body", headline: "A family friend's import business needed help with pricing", supportingText: "" },
      { role: "body", headline: "I said yes before I knew if I could actually do it", supportingText: "" },
      { role: "body", headline: "That first project paid almost nothing. It taught me everything", supportingText: "" },
      { role: "body", headline: "One client turned into three, then into an actual practice", supportingText: "" },
      { role: "body", headline: "Six years later: 30+ clients, 15 industries, 6 countries", supportingText: "" },
      { role: "cta", headline: "Follow for more of how this business actually started", supportingText: "" },
    ],
  },
  {
    title: "The Client Who Almost Made Me Quit Consulting",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "follow",
    funnelStage: "mofu",
    topicTag: "Early Struggles",
    segment: "Lesson Learned",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Muted slate solid background, confessional tone, medium-weight sans-serif body text.",
    slides: [
      { role: "hook", headline: "The client who almost made me quit consulting", supportingText: "" },
      { role: "body", headline: "Year 2, I took a client purely for the revenue", supportingText: "" },
      { role: "body", headline: "The fit was wrong from the first call, I ignored it anyway", supportingText: "" },
      { role: "body", headline: "Every deliverable got rewritten 4, 5, 6 times", supportingText: "" },
      { role: "body", headline: "I started dreading my own calendar", supportingText: "" },
      { role: "body", headline: "The project ended badly, I almost closed the business over it", supportingText: "" },
      { role: "body", headline: "What saved it: the client wasn't the problem, my vetting was", supportingText: "" },
      { role: "body", headline: "That project is the whole reason I built a client-fit checklist", supportingText: "" },
      { role: "cta", headline: "Follow for how that checklist still protects every project", supportingText: "" },
    ],
  },
  {
    title: "How One Rejected Proposal Built My Entire Process",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Early Lessons",
    segment: "Founder Story",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Soft rose-to-amber gradient, warm reflective tone, serif headline for an editorial feel.",
    slides: [
      { role: "hook", headline: "How one rejected proposal built my entire process", supportingText: "" },
      { role: "body", headline: "Year 1, I sent a proposal I was genuinely proud of", supportingText: "" },
      { role: "body", headline: "The client went with someone else, no explanation given", supportingText: "" },
      { role: "body", headline: "I asked for feedback anyway, most people don't", supportingText: "" },
      { role: "body", headline: "They said my price looked arbitrary, like a guess", supportingText: "" },
      { role: "body", headline: "I had no breakdown, no comparable, nothing to back it up", supportingText: "" },
      { role: "body", headline: "I rebuilt how I price every project after that conversation", supportingText: "" },
      { role: "body", headline: "Every proposal since has math a client can actually see", supportingText: "" },
      { role: "cta", headline: "Follow for more lessons that came from losing, not winning", supportingText: "" },
    ],
  },
  {
    title: "From Free Advice to a 6-Country Consulting Practice",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "link",
    funnelStage: "bofu",
    topicTag: "Business Growth",
    segment: "Founder Story",
    backgroundStyle: "photo",
    backgroundCategory: "window_light",
    designNotes: "Soft window-light photo background, calm aspirational mood, warm white headline text.",
    slides: [
      { role: "hook", headline: "From free advice to a 6-country consulting practice", supportingText: "" },
      { role: "body", headline: "The first year, almost everything I gave away was free", supportingText: "" },
      { role: "body", headline: "I told myself I was 'building relationships'", supportingText: "" },
      { role: "body", headline: "I was actually avoiding the conversation about value", supportingText: "" },
      { role: "body", headline: "The shift started with one client who insisted on paying me", supportingText: "" },
      { role: "body", headline: "That forced me to actually price the work, for the first time", supportingText: "" },
      { role: "body", headline: "Every client after that paid from day one, no exceptions", supportingText: "" },
      { role: "body", headline: "That one boundary is most of what got this to 6 countries", supportingText: "" },
      { role: "cta", headline: "Link in bio if you're ready to stop giving your expertise away", supportingText: "" },
    ],
  },
  {
    title: "The Year I Almost Shut This Business Down",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "story_arc",
    ctaType: "comment",
    funnelStage: "mofu",
    topicTag: "Business Resilience",
    segment: "Founder Story",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Muted burgundy solid background, honest confessional tone, clean sans-serif body text.",
    slides: [
      { role: "hook", headline: "The year I almost shut this business down", supportingText: "" },
      { role: "body", headline: "Year 3, three clients paused projects in the same quarter", supportingText: "" },
      { role: "body", headline: "I'd built the business around relationships, not a system", supportingText: "" },
      { role: "body", headline: "For two months, I seriously looked at job listings", supportingText: "" },
      { role: "body", headline: "What stopped me was one old client calling with a new project", supportingText: "" },
      { role: "body", headline: "That call made me ask why referrals were my only pipeline", supportingText: "" },
      { role: "body", headline: "I rebuilt outreach, content, and follow-up from scratch", supportingText: "" },
      { role: "body", headline: "The business today is sturdier because that year nearly broke it", supportingText: "" },
      { role: "cta", headline: "Comment YEAR3 if you've had your own version of this", supportingText: "" },
    ],
  },

  // ---------- Quote / Mindset Chain (4) ----------
  {
    title: "Nobody Builds a Business on Confidence Alone",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "quote_chain",
    ctaType: "follow",
    funnelStage: "tofu",
    topicTag: "Founder Mindset",
    segment: "Mindset",
    backgroundStyle: "minimalist",
    backgroundCategory: "",
    designNotes: "Pale neutral minimalist background, low text density, heavy typographic weight per statement.",
    slides: [
      { role: "hook", headline: "Nobody builds a business on confidence alone", supportingText: "" },
      { role: "body", headline: "Confidence is a byproduct of reps, not a prerequisite for them", supportingText: "" },
      { role: "body", headline: "You will feel unqualified for the version of you that's coming", supportingText: "" },
      { role: "body", headline: "Every client I've signed, I signed while still doubting myself", supportingText: "" },
      { role: "body", headline: "The doubt doesn't disappear, you just get faster past it", supportingText: "" },
      { role: "body", headline: "Discipline shows up before confidence does, every single time", supportingText: "" },
      { role: "cta", headline: "Follow for more of the mindset side of building this", supportingText: "" },
    ],
  },
  {
    title: "Things I Tell Every First-Time Founder",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "quote_chain",
    ctaType: "save",
    funnelStage: "tofu",
    topicTag: "Founder Advice",
    segment: "Mindset",
    backgroundStyle: "solid",
    backgroundCategory: "",
    designNotes: "Warm cream solid background, bold black statement per slide, no imagery, high contrast type.",
    slides: [
      { role: "hook", headline: "Things I tell every first-time founder", supportingText: "" },
      { role: "body", headline: "Your first client is not your forever client", supportingText: "" },
      { role: "body", headline: "Being underestimated is leverage, not a liability", supportingText: "" },
      { role: "body", headline: "A no today is data, not a verdict on the idea", supportingText: "" },
      { role: "body", headline: "Specific beats impressive, every single time", supportingText: "" },
      { role: "body", headline: "The market tells you the truth faster than any mentor will", supportingText: "" },
      { role: "cta", headline: "Save this for the next time you need to hear it", supportingText: "" },
    ],
  },
  {
    title: "What 6 Years of Consulting Taught Me About Risk",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "quote_chain",
    ctaType: "follow",
    funnelStage: "mofu",
    topicTag: "Risk & Decision-Making",
    segment: "Mindset",
    backgroundStyle: "gradient",
    backgroundCategory: "",
    designNotes: "Steel blue-to-charcoal gradient, bold centered statements, thin divider line between slides.",
    slides: [
      { role: "hook", headline: "What 6 years of consulting taught me about risk", supportingText: "" },
      { role: "body", headline: "The riskiest move is usually the one that feels safest", supportingText: "" },
      { role: "body", headline: "Staying in a market too long costs more than leaving too soon", supportingText: "" },
      { role: "body", headline: "Every client who waited for 'certain' waited too long", supportingText: "" },
      { role: "body", headline: "Risk isn't the enemy, an unsized bet is", supportingText: "" },
      { role: "body", headline: "I've never regretted a decision I actually sized before making it", supportingText: "" },
      { role: "cta", headline: "Follow for more of what this work keeps teaching me", supportingText: "" },
    ],
  },
  {
    title: "Read This Before You Quit Your Safe Job",
    pillar: "journey",
    contentType: "storytelling",
    archetype: "quote_chain",
    ctaType: "share",
    funnelStage: "tofu",
    topicTag: "Career Transitions",
    segment: "Mindset",
    backgroundStyle: "photo",
    backgroundCategory: "window_light",
    designNotes: "Soft window-light photo background, calm silhouette mood, warm white statement text.",
    slides: [
      { role: "hook", headline: "Read this before you quit your safe job", supportingText: "" },
      { role: "body", headline: "A safe job isn't the enemy, staying for the wrong reason is", supportingText: "" },
      { role: "body", headline: "I never had a safe job to quit, I had to build the floor myself", supportingText: "" },
      { role: "body", headline: "Either path works if you're honest about which you're choosing", supportingText: "" },
      { role: "body", headline: "The scariest part isn't leaving, it's the six months after", supportingText: "" },
      { role: "body", headline: "Plan for those six months harder than you plan the decision", supportingText: "" },
      { role: "cta", headline: "Send this to someone deciding whether to make the jump", supportingText: "" },
    ],
  },
];
