// Gap-fill batch: the journey/storytelling pillar had only 5 scripts total
// (vs 558 in the authority pillar), with 4 of 7 story types at zero. This
// batch adds 40 personal-narrative scripts across all 7 STORY_TYPES,
// bringing journey to a comparable floor with every other topic/segment
// (which already sit at 4-10 each). Same craft-rules pattern as every
// other batch. Continues the weekly cadence right after Phase 6 (28 items
// at NEW_CATEGORIES_6_START_WEEK=535, weekOffset 0-27 -> occupies weeks
// 535-562), starting at week 563. Consistent with the founder persona
// already established in octBatch.ts's 5 journey scripts: started
// consulting around 18-19, market-entry & business consulting for MSMEs,
// clients across industries.

import type { BatchScript } from "./octBatch";
import { BASE_DATE } from "./octBatch";

export { BASE_DATE };
export const JOURNEY_START_WEEK = 563;
export const JOURNEY_BATCH_TAG = "journey_storytelling_40_batch_v1";

export type JourneyScript = BatchScript & { topicTag: string };

const T = "follow" as const;
const M = "engagement" as const;
const B = "manychat" as const;

export const JOURNEY_BATCH: JourneyScript[] = [
  // ---------- My Story (6) ----------
  {
    weekOffset: 0, topicTag: "Founder Journey",
    title: "How I Went From Failing My Entrance Exams to Running a Consulting Business",
    pillar: "journey", contentType: "storytelling", angle: "My Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "At 18, I failed my entrance exams. Everyone around me had a plan. I had none.\nI spent the next year doing small research gigs for local businesses -- nothing glamorous, only answering questions nobody else wanted to.\nOne of those small gigs turned into my first real consulting client. That client referred two more.\nI never planned to build a consulting business. I backed into it one unglamorous project at a time.",
    bodyRed: "Warm, reflective tone throughout -- no dramatic camera moves.", bodyGreen: "On-screen text: \"18, no plan\" fading into \"first client\" as the story progresses.",
    ctaLine: "Follow if you're still figuring out your own version of this.",
  },
  {
    weekOffset: 1, topicTag: "Founder Journey",
    title: "The First Client I Ever Had, and What They Taught Me",
    pillar: "journey", contentType: "storytelling", angle: "My Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "My first client was a small import business run by a man who'd never had anyone question his pricing before.\nI was nervous walking in. I had no case studies, no track record, nothing but a notebook full of questions.\nHe took a chance on me because I asked better questions than the last three consultants he'd talked to.\nThat's still the whole job, years later -- asking the question nobody else bothered to ask.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "On-screen text: key line \"asking the question nobody else asked\" highlighted.",
    ctaLine: "Follow for more of how this business actually started.",
  },
  {
    weekOffset: 2, topicTag: "Founder Journey",
    title: "Why I Chose Market-Entry Consulting When Everyone Told Me to Get a Job",
    pillar: "journey", contentType: "storytelling", angle: "My Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "Every relative had the same advice: get a stable job, this consulting thing isn't a real career yet.\nI understood the concern. I had no safety net, no connections, no guarantee any of this would work.\nWhat I did have was a genuine interest in why some small businesses expanded successfully and most didn't.\nThat specific curiosity, followed for a few years, turned into an actual business. The safe advice wasn't wrong to worry -- it was only optimizing for a different outcome than the one I wanted.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "On-screen text: \"everyone said get a job\" then \"I asked why instead\".",
    ctaLine: "Follow if you're weighing the same decision right now.",
  },
  {
    weekOffset: 3, topicTag: "Founder Journey",
    title: "The Moment I Realized I Actually Understood This Industry",
    pillar: "journey", contentType: "storytelling", angle: "My Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "For the first two years, I felt like I was guessing every time a client asked a hard question.\nThen one day, mid-meeting, a client asked something I'd been asked a dozen times before -- and I answered without hesitating, without checking notes.\nThat was the moment it stopped feeling like I was pretending to know this industry and started feeling like I actually did.\nComment \"JOURNEY\" if you've had that exact moment in your own work.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "Comment prompt: \"Comment JOURNEY\".",
    ctaLine: "Comment JOURNEY if you've felt this moment yourself.",
  },
  {
    weekOffset: 4, topicTag: "Founder Journey",
    title: "What Nobody Tells You About Starting a Consulting Business Young",
    pillar: "journey", contentType: "storytelling", angle: "My Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "People assume starting young means more energy and fewer obligations. That part's true.\nWhat nobody mentions: clients sometimes take one look at your age and decide before you've said a word.\nI learned to let the work answer that question instead of trying to argue my way past it in the first meeting.\nAge stopped being the obstacle once the results did the talking.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "On-screen text: \"let the work answer it\".",
    ctaLine: "Follow if you're building something people underestimate.",
  },
  {
    weekOffset: 5, topicTag: "Founder Journey",
    title: "How a Conversation With My Father Changed How I Run This Business",
    pillar: "journey", contentType: "storytelling", angle: "My Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "Early on, I was taking every client that would pay, regardless of fit.\nMy father, who'd run a small business for 20 years, asked me one question: \"would you actually recommend yourself to a friend for this line of work?\"\nFor some of those clients, honestly, the answer was no. I was solving the wrong problem for them.\nThat one question changed which clients I take on to this day.\nComment \"FIT\" and I'll send you the client-fit checklist that question turned into.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "Comment prompt: \"Comment FIT\".",
    ctaLine: "Comment FIT and I'll send you the client-fit checklist.",
  },

  // ---------- Win Story (6) ----------
  {
    weekOffset: 6, topicTag: "Founder Journey",
    title: "The Client Win That Made Me Believe This Business Could Actually Work",
    pillar: "journey", contentType: "storytelling", angle: "Win Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "Two years in, a client was about to shelve their expansion plan after a failed first attempt.\nWe rebuilt their entry approach from scratch -- different market segment, different pricing, different pilot structure.\nSix months later, that market became their single largest revenue source.\nThat one result is what made me stop wondering if this business would actually work.\nComment \"WIN\" and I'll walk you through exactly what we changed.",
    bodyRed: "Warm, energetic tone as the win lands.", bodyGreen: "Comment prompt: \"Comment WIN\".",
    ctaLine: "Comment WIN and I'll walk you through what we changed.",
  },
  {
    weekOffset: 7, topicTag: "Founder Journey",
    title: "The First Time a Client Called Me Instead of the Other Way Around",
    pillar: "journey", contentType: "storytelling", angle: "Win Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "For the first year and a half, I was the one chasing every conversation.\nThen one afternoon, a business owner I'd never met called me directly, referred by a past client, already sure they wanted to work together.\nI almost didn't know what to say -- I'd never had a conversation start from that side of the table before.\nThat call is still the clearest marker of when word of mouth started doing real work for this business.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "On-screen text: \"the call I didn't have to make\".",
    ctaLine: "Follow for how I built that word of mouth deliberately.",
  },
  {
    weekOffset: 8, topicTag: "Founder Journey",
    title: "The Deal I Almost Walked Away From That Became My Biggest Client",
    pillar: "journey", contentType: "storytelling", angle: "Win Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "Their budget was smaller than I usually took on, and honestly, I almost passed.\nSomething about how specific their questions were made me say yes anyway.\nThat small first project led to three more phases over the next year, and they became the largest client this business has ever had.\nThe lesson stuck: budget size told me less about fit than the quality of their questions did.\nComment \"BIGGEST\" and I'll tell you the full story.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "Comment prompt: \"Comment BIGGEST\".",
    ctaLine: "Comment BIGGEST and I'll tell you the full story.",
  },
  {
    weekOffset: 9, topicTag: "Founder Journey",
    title: "The Win That Proved the Framework I Teach Actually Works",
    pillar: "journey", contentType: "storytelling", angle: "Win Story", format: "Voiceover Format",
    funnelStage: "bofu", ctaType: B, conceptBucket: "proven", effort: "high",
    bodyBlack: "I'd been teaching a 3-phase market-entry framework for a year before I got to use it on a client from day one, start to finish.\nPhase 1 caught a segment mismatch that would have cost them months. Phase 2 caught a pricing error before launch. Phase 3 turned the pilot into a repeatable playbook.\nWatching every phase catch a real problem, in order, on an actual client, is what convinced me the framework wasn't only a good idea on paper.\nComment \"FRAMEWORK\" and I'll DM you the same 3-phase breakdown.",
    bodyRed: "Warm, energetic tone as each phase lands.", bodyGreen: "Comment prompt: \"Comment FRAMEWORK\".",
    ctaLine: "Comment FRAMEWORK and I'll DM you the 3-phase breakdown.",
  },
  {
    weekOffset: 10, topicTag: "Founder Journey",
    title: "The Small Win Early On That Kept Me From Quitting",
    pillar: "journey", contentType: "storytelling", angle: "Win Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "Six months in, I was close to giving up on this entirely. The pipeline was thin and the doubt was loud.\nThen a small client, someone I'd nearly turned down, left a review that specifically named the one thing I'd worried I wasn't good at.\nIt wasn't a big project. It wasn't a big payday. It was only proof that the thing I was scared I couldn't do, I could actually do.\nThat review is still saved on my phone.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "On-screen text: \"the review I still have saved\".",
    ctaLine: "Follow if you need a reminder that small wins count.",
  },
  {
    weekOffset: 11, topicTag: "Founder Journey",
    title: "The Win I'm Proudest of That Has Nothing to Do With Revenue",
    pillar: "journey", contentType: "storytelling", angle: "Win Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "The project that made the most money wasn't the one that meant the most.\nThe one I'm proudest of: a client who'd been rejected by three consultants before me, told they were too small to bother helping properly.\nWe worked together for four months, and their business is still growing two years later.\nRevenue numbers fade. That specific kind doesn't.\nComment \"PROUD\" and I'll tell you the rest of that story.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "Comment prompt: \"Comment PROUD\".",
    ctaLine: "Comment PROUD and I'll tell you the rest of that story.",
  },

  // ---------- Loss Story (7, joining the existing 2 -> 9 total) ----------
  {
    weekOffset: 12, topicTag: "Founder Journey",
    title: "The Client I Lost Because I Was Too Afraid to Push Back",
    pillar: "journey", contentType: "storytelling", angle: "Loss Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "Early on, a client kept pushing the project in a direction I knew wouldn't work.\nI went along with it because I was scared of losing the client if I disagreed.\nThe project failed, and I lost them anyway -- for the outcome I'd known was coming, not for pushing back.\nI learned the disagreement I was avoiding was cheaper than the failure I was avoiding it toward.\nComment \"PUSHBACK\" and I'll tell you how I handle that conversation differently now.",
    bodyRed: "Slower, more reflective tone.", bodyGreen: "Comment prompt: \"Comment PUSHBACK\".",
    ctaLine: "Comment PUSHBACK and I'll tell you how I do it differently now.",
  },
  {
    weekOffset: 13, topicTag: "Founder Journey",
    title: "The Project That Failed Because I Skipped the Research Phase",
    pillar: "journey", contentType: "storytelling", angle: "Loss Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "A client was in a hurry, and I let their urgency skip a step I never skip anymore.\nWe went straight to a launch plan without properly validating the segment first.\nThe launch underperformed badly, and the postmortem traced it straight back to that skipped step.\nI've never skipped that step again, no matter how urgent a client's timeline feels.",
    bodyRed: "Slower, more reflective tone.", bodyGreen: "On-screen text: \"the step I never skip again\".",
    ctaLine: "Follow for the step I now refuse to skip, no matter the timeline.",
  },
  {
    weekOffset: 14, topicTag: "Founder Journey",
    title: "The Referral I Lost Because I Didn't Follow Up",
    pillar: "journey", contentType: "storytelling", angle: "Loss Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "A past client mentioned they knew someone who might need help. I said \"send them my way\" and never followed up.\nMonths later I found out that referral had gone to someone else entirely, simply because I never made it easy or specific.\nIt was a small, forgettable moment for me. For my business, it was a lost client I never even got the chance to talk to.\nThat loss is exactly why I built a real referral process instead of hoping people remember.",
    bodyRed: "Slower, more reflective tone.", bodyGreen: "On-screen text: \"the referral I let go cold\".",
    ctaLine: "Follow for the referral system I built after that.",
  },
  {
    weekOffset: 15, topicTag: "Founder Journey",
    title: "The Time I Underpriced a Project So Badly It Almost Broke Me",
    pillar: "journey", contentType: "storytelling", angle: "Loss Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "I quoted a project based on what I thought I should charge, not what the work actually required.\nThree months in, I was working nights and weekends on a fee that didn't come close to covering the hours.\nI finished the project because I'd committed to it, but I nearly burned out doing it.\nThat project is the reason I rebuilt how I price everything, from the ground up.\nComment \"PRICING\" and I'll send you what changed.",
    bodyRed: "Slower, more reflective tone.", bodyGreen: "Comment prompt: \"Comment PRICING\".",
    ctaLine: "Comment PRICING and I'll send you what changed.",
  },
  {
    weekOffset: 16, topicTag: "Founder Journey",
    title: "The Partnership That Fell Apart, and What I Missed Before It Started",
    pillar: "journey", contentType: "storytelling", angle: "Loss Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "A promising partnership fell apart eight months in, over something we'd never actually agreed on in writing.\nWe'd both assumed we understood the split, the roles, the exit -- we'd never once written any of it down.\nLosing that partnership cost more than money. It cost a relationship I'd valued.\nEverything I now put in writing before a partnership starts traces back to that specific loss.\nComment \"PARTNER\" and I'll send you what I put in writing now.",
    bodyRed: "Slower, more reflective tone.", bodyGreen: "Comment prompt: \"Comment PARTNER\".",
    ctaLine: "Comment PARTNER and I'll send you what I put in writing now.",
  },
  {
    weekOffset: 17, topicTag: "Founder Journey",
    title: "The Year Revenue Dropped and What I Almost Did Wrong",
    pillar: "journey", contentType: "storytelling", angle: "Loss Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "One year, revenue dropped nearly 40% with no single clear cause.\nMy first instinct was to panic and chase every lead regardless of fit, only to fill the gap.\nA mentor talked me out of it -- said chasing bad-fit clients out of fear usually makes a bad year worse, not better.\nI held the line on fit instead, and the following year recovered fully. The panic would have cost more than the dip did.",
    bodyRed: "Slower, more reflective tone.", bodyGreen: "On-screen text: \"the panic would have cost more\".",
    ctaLine: "Follow for how I actually rebuilt after that year.",
  },
  {
    weekOffset: 18, topicTag: "Founder Journey",
    title: "The Feedback I Got Wrong for Two Years Before I Actually Heard It",
    pillar: "journey", contentType: "storytelling", angle: "Loss Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "Multiple clients, over two separate years, mentioned the same thing in slightly different words. I dismissed it every time.\nIt took a third client stating it bluntly for me to actually hear what they'd all been telling me.\nOnce I finally changed it, client satisfaction and referrals both improved noticeably within a single quarter.\nTwo years of the same feedback, and I only heard it on the third direct version of it.\nComment \"FEEDBACK\" and I'll tell you what it was.",
    bodyRed: "Slower, more reflective tone.", bodyGreen: "Comment prompt: \"Comment FEEDBACK\".",
    ctaLine: "Comment FEEDBACK and I'll tell you what it was.",
  },

  // ---------- Lesson Story (7, joining the existing 2 -> 9 total) ----------
  {
    weekOffset: 19, topicTag: "Founder Journey",
    title: "What a Failed Pitch Taught Me About Reading a Room",
    pillar: "journey", contentType: "storytelling", angle: "Lesson Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "I once pitched an idea to a room that had clearly already made up its mind before I walked in.\nI kept pitching anyway, adding more detail, more slides, more conviction. None of it moved the room.\nAfterward, someone told me the decision had been made the week before -- nothing I said that day was ever going to change it.\nNow I read the room before I pitch anything, not only after it goes wrong.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "On-screen text: \"the decision was already made\".",
    ctaLine: "Follow for how I read a room before pitching now.",
  },
  {
    weekOffset: 20, topicTag: "Founder Journey",
    title: "What Working With My Hardest Client Taught Me About Boundaries",
    pillar: "journey", contentType: "storytelling", angle: "Lesson Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "One client called or messaged at nearly every hour, expecting an immediate answer every time.\nI answered immediately for months, training them, without meaning to, that any hour was fine.\nWhen I finally set clear response-time boundaries, they respected it instantly -- the behavior had been mine to allow, not theirs to force.\nThat client taught me more about boundaries than any book on the subject ever did.\nComment \"BOUNDARY\" and I'll send you the exact boundary I set.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "Comment prompt: \"Comment BOUNDARY\".",
    ctaLine: "Comment BOUNDARY and I'll send you the exact boundary I set.",
  },
  {
    weekOffset: 21, topicTag: "Founder Journey",
    title: "What a Rejected Proposal Taught Me About Pricing Confidence",
    pillar: "journey", contentType: "storytelling", angle: "Lesson Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "I once halved my rate mid-conversation the moment a prospect hesitated, before they'd even objected.\nThey still didn't sign. I'd given away margin for nothing, purely out of my own nervousness.\nThe lesson wasn't about the specific number -- it was that hesitation on my end read as doubt about my own value.\nI've never dropped a rate reactively again. If it changes, it changes on purpose.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "On-screen text: \"hesitation reads as doubt\".",
    ctaLine: "Follow for how I hold my pricing steady now.",
  },
  {
    weekOffset: 22, topicTag: "Founder Journey",
    title: "What a Bad Hire Taught Me About Trusting My Gut",
    pillar: "journey", contentType: "storytelling", angle: "Lesson Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "I had a nagging doubt in the interview and hired anyway, because the resume looked strong on paper.\nThe doubt turned out to be right. It cost months untangling work that had to be redone from scratch.\nSince then, I treat a real gut doubt in an interview as data worth weighing, not something to talk myself out of.\nComment \"HIRE\" and I'll send you what I changed about how I interview now.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "Comment prompt: \"Comment HIRE\".",
    ctaLine: "Comment HIRE and I'll send you what I changed.",
  },
  {
    weekOffset: 23, topicTag: "Founder Journey",
    title: "What Losing My First Big Client Taught Me About Revenue Concentration",
    pillar: "journey", contentType: "storytelling", angle: "Lesson Story", format: "Voiceover Format",
    funnelStage: "bofu", ctaType: B, conceptBucket: "proven", effort: "high",
    bodyBlack: "One client made up nearly half my revenue for over a year. When they left, it wasn't dramatic -- their own budget changed, nothing more.\nThe drop in income was immediate and much bigger than I'd braced for, because I'd never actually modeled what losing them would mean.\nSince then, I cap how much any single client can represent of total revenue, and I actually track it every quarter.\nComment \"CONCENTRATE\" and I'll DM you the exact cap I use and how I track it.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "Comment prompt: \"Comment CONCENTRATE\".",
    ctaLine: "Comment CONCENTRATE and I'll DM you the cap I use.",
  },
  {
    weekOffset: 24, topicTag: "Founder Journey",
    title: "What a Long Silence From a Client Taught Me About Following Up",
    pillar: "journey", contentType: "storytelling", angle: "Lesson Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "A promising client conversation went quiet for three weeks, and I assumed that silence meant no.\nI moved on entirely. Months later I learned they'd simply been dealing with an internal emergency, unrelated to our conversation.\nBy the time they were ready, they'd already signed with someone else who'd stayed in touch.\nI follow up now assuming the silence means nothing specific, not that it means no.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "On-screen text: \"silence doesn't always mean no\".",
    ctaLine: "Follow for how I follow up now instead of assuming.",
  },
  {
    weekOffset: 25, topicTag: "Founder Journey",
    title: "What Turning Down My Biggest Potential Client Taught Me About Fit",
    pillar: "journey", contentType: "storytelling", angle: "Lesson Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "The largest deal I'd ever been offered came with a request that conflicted directly with how I actually work.\nTaking it would have meant compromising the exact process that made my results worth paying for in the first place.\nI turned it down. It was uncomfortable in the moment and completely right in hindsight.\nThat decision is the clearest line I have for what fit actually means to me now.\nComment \"TURNDOWN\" and I'll tell you the full story.",
    bodyRed: "Warm, reflective tone.", bodyGreen: "Comment prompt: \"Comment TURNDOWN\".",
    ctaLine: "Comment TURNDOWN and I'll tell you the full story.",
  },

  // ---------- Transformation Story (5) ----------
  {
    weekOffset: 26, topicTag: "Founder Journey",
    title: "From Answering Every Message Instantly to Actually Having Boundaries",
    pillar: "journey", contentType: "storytelling", angle: "Transformation Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "For the first two years, I answered every client message within minutes, day or night, weekends included.\nIt felt like good service. It was actually a slow path to burnout, and it trained clients to expect it permanently.\nThe transformation wasn't dramatic -- I set specific response windows and stuck to them, even when it felt uncomfortable at first.\nClients adjusted within weeks. My actual quality of work improved once I wasn't perpetually reactive.\nComment \"BOUNDARIES\" and I'll send you the exact response windows I use.",
    bodyRed: "Reflective tone shifting to confident by the end.", bodyGreen: "Comment prompt: \"Comment BOUNDARIES\".",
    ctaLine: "Comment BOUNDARIES and I'll send you the response windows I use.",
  },
  {
    weekOffset: 27, topicTag: "Founder Journey",
    title: "From Underpricing Every Project to Charging What the Work Is Actually Worth",
    pillar: "journey", contentType: "storytelling", angle: "Transformation Story", format: "Voiceover Format",
    funnelStage: "bofu", ctaType: B, conceptBucket: "proven", effort: "high",
    bodyBlack: "For years, I priced based on what I thought I deserved, which was almost always less than the value delivered.\nThe transformation started with a single uncomfortable conversation, naming a number that felt too high, and having a client say yes anyway.\nOnce that first higher number landed, I never went back to pricing from fear again.\nRevenue nearly doubled over the following year, on fewer total clients, doing better work for each one.\nComment \"REPRICE\" and I'll DM you exactly how I made that first jump.",
    bodyRed: "Reflective tone shifting to confident by the end.", bodyGreen: "Comment prompt: \"Comment REPRICE\".",
    ctaLine: "Comment REPRICE and I'll DM you how I made that jump.",
  },
  {
    weekOffset: 28, topicTag: "Founder Journey",
    title: "From Doing Everything Myself to Actually Building a Team",
    pillar: "journey", contentType: "storytelling", angle: "Transformation Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "For a long time, I believed no one could do the work as well as I could, so I never delegated anything real.\nThat belief capped how much the business could ever grow, no matter how many hours I added.\nThe shift started with handing off one small, low-stakes task, watching it get done well, and handing off another.\nA year later, a real team handles work I once thought only I could do -- and it's often done better than I did it alone.\nComment \"DELEGATE\" and I'll send you how I picked that first task to hand off.",
    bodyRed: "Reflective tone shifting to confident by the end.", bodyGreen: "Comment prompt: \"Comment DELEGATE\".",
    ctaLine: "Comment DELEGATE and I'll send you how I picked that first task.",
  },
  {
    weekOffset: 29, topicTag: "Founder Journey",
    title: "From Taking Any Client Who'd Pay to Having an Actual Waitlist",
    pillar: "journey", contentType: "storytelling", angle: "Transformation Story", format: "Voiceover Format",
    funnelStage: "bofu", ctaType: B, conceptBucket: "proven", effort: "high",
    bodyBlack: "In the early years, saying yes to any paying client felt like the only responsible move.\nThat approach filled the calendar with mismatched work and left no room for the clients who were actually the best fit.\nDefining a specific client profile, and saying no to anyone outside it, felt reckless the first few times.\nNow there's a waitlist made up entirely of the exact client type that early version of the business would have been too scared to turn away others for.\nComment \"WAITLIST\" and I'll DM you the exact profile I use to decide.",
    bodyRed: "Reflective tone shifting to confident by the end.", bodyGreen: "Comment prompt: \"Comment WAITLIST\".",
    ctaLine: "Comment WAITLIST and I'll DM you the client profile I use.",
  },
  {
    weekOffset: 30, topicTag: "Founder Journey",
    title: "From Guessing at Every Client Problem to Having an Actual Process",
    pillar: "journey", contentType: "storytelling", angle: "Transformation Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "Every project used to start from scratch -- new approach, new structure, entirely improvised each time.\nThat meant every client got an inconsistent experience, and I relearned the same lessons project after project.\nDocumenting the actual process, step by step, after enough projects to see the pattern, changed the quality overnight.\nNew clients now get a proven structure instead of an improvised one, and results became far more consistent.\nComment \"PROCESS\" and I'll send you how I documented mine.",
    bodyRed: "Reflective tone shifting to confident by the end.", bodyGreen: "Comment prompt: \"Comment PROCESS\".",
    ctaLine: "Comment PROCESS and I'll send you how I documented mine.",
  },

  // ---------- Challenge Story (5) ----------
  {
    weekOffset: 31, topicTag: "Founder Journey",
    title: "The Month I Almost Shut This Business Down",
    pillar: "journey", contentType: "storytelling", angle: "Challenge Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "Three clients paused their projects in the same month, with no warning and no connection between them.\nThe pipeline behind them was thin, and for the first time, I seriously considered closing the business and finding a job instead.\nI gave myself two weeks to either find a real path forward or make peace with stopping.\nA single overdue follow-up email, sent in that window, turned into the client that carried the business through the next quarter.",
    bodyRed: "Tense tone easing into relief by the end.", bodyGreen: "On-screen text: \"two weeks to decide\".",
    ctaLine: "Follow for what that follow-up email actually said.",
  },
  {
    weekOffset: 32, topicTag: "Founder Journey",
    title: "How I Kept the Business Running Through a Brutal Cash Crunch",
    pillar: "journey", contentType: "storytelling", angle: "Challenge Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "Two large invoices went unpaid for months at the same time expenses kept coming due regardless.\nI cut every non-essential cost within a week and had an honest conversation with both clients about payment terms.\nOne client paid within days once I actually asked directly instead of hoping they'd remember on their own.\nThat crunch is the reason I built a real cash buffer and never let a single client's payment timing control the business again.\nComment \"CASHCRUNCH\" and I'll send you what I changed after that.",
    bodyRed: "Tense tone easing into relief by the end.", bodyGreen: "Comment prompt: \"Comment CASHCRUNCH\".",
    ctaLine: "Comment CASHCRUNCH and I'll send you what I changed.",
  },
  {
    weekOffset: 33, topicTag: "Founder Journey",
    title: "The Project That Fell Apart Mid-Delivery and How I Handled It",
    pillar: "journey", contentType: "storytelling", angle: "Challenge Story", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "Halfway through a project, the client's own internal team changed direction entirely, making half our completed work irrelevant.\nMy first instinct was frustration, but the client hadn't done anything wrong -- their business had simply changed.\nI proposed a scoped revision instead of treating it as a dead project, and we finished on a version that actually fit their new direction.\nStaying calm and flexible in that moment kept a client who could easily have walked away frustrated instead.",
    bodyRed: "Tense tone easing into relief by the end.", bodyGreen: "On-screen text: \"the client hadn't done anything wrong\".",
    ctaLine: "Follow for how I handle a mid-project pivot now.",
  },
  {
    weekOffset: 34, topicTag: "Founder Journey",
    title: "The Year I Had to Rebuild My Entire Client Base From Almost Nothing",
    pillar: "journey", contentType: "storytelling", angle: "Challenge Story", format: "Voiceover Format",
    funnelStage: "bofu", ctaType: B, conceptBucket: "proven", effort: "high",
    bodyBlack: "A shift in my own niche focus meant most of my existing client base no longer fit the work I wanted to do.\nI had to let go of stable, familiar clients and rebuild an entirely new base around the sharper focus.\nThe first few months were the leanest this business has ever had, and there were real moments of doubting the decision.\nA year later, the new client base was both more profitable and more aligned with the work I actually wanted to keep doing.\nComment \"REBUILD\" and I'll DM you how I managed the transition without losing everything.",
    bodyRed: "Tense tone easing into relief by the end.", bodyGreen: "Comment prompt: \"Comment REBUILD\".",
    ctaLine: "Comment REBUILD and I'll DM you how I managed the transition.",
  },
  {
    weekOffset: 35, topicTag: "Founder Journey",
    title: "The Client Emergency That Tested Everything I Thought I Knew About Crisis Management",
    pillar: "journey", contentType: "storytelling", angle: "Challenge Story", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "A client's launch went badly wrong in full public view, and they called me in a genuine panic.\nEverything I'd ever read about staying calm under pressure got tested in real time, with no room to prepare.\nWe worked through it methodically -- assess the actual damage first, then act, instead of reacting to the panic in the room.\nThe client later said that calm, structured response was what kept the situation from becoming worse than it already was.\nComment \"CRISIS\" and I'll send you the exact steps we took that day.",
    bodyRed: "Tense tone easing into relief by the end.", bodyGreen: "Comment prompt: \"Comment CRISIS\".",
    ctaLine: "Comment CRISIS and I'll send you the exact steps we took.",
  },

  // ---------- Big Goal / Dream Journey (5) ----------
  {
    weekOffset: 36, topicTag: "Founder Journey",
    title: "Why I'm Building Toward Helping 1,000 Small Businesses Enter New Markets",
    pillar: "journey", contentType: "storytelling", angle: "Big Goal / Dream Journey", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "The goal sounds large when I say it out loud: 1,000 small businesses helped into new markets, not only a handful of big clients.\nI didn't start with that number. It came from watching how much a single successful expansion changed one business's entire trajectory.\nEvery framework I build, every piece of content I make, is one small step toward that larger number.\nI'm nowhere near it yet. I'm sharing the whole path there, not only the finished version of it.",
    bodyRed: "Aspirational, warm tone.", bodyGreen: "On-screen text: \"1,000 businesses -- the real number I'm working toward\".",
    ctaLine: "Follow to watch this goal actually get built, in public.",
  },
  {
    weekOffset: 37, topicTag: "Founder Journey",
    title: "The 5-Year Vision Behind Everything I'm Building Right Now",
    pillar: "journey", contentType: "storytelling", angle: "Big Goal / Dream Journey", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "In 5 years, I want this to be the first name that comes up when a small business thinks about entering a new market.\nThat means the content I make today, the frameworks I refine, the clients I take on -- all of it is building toward that one specific outcome.\nIt's a long way from where things stand right now, and I'm honest about that distance rather than pretending it's already closer.\nComment \"VISION\" and I'll share the actual milestones I'm tracking toward it.",
    bodyRed: "Aspirational, warm tone.", bodyGreen: "Comment prompt: \"Comment VISION\".",
    ctaLine: "Comment VISION and I'll share the milestones I'm tracking.",
  },
  {
    weekOffset: 38, topicTag: "Founder Journey",
    title: "Why Building This in Public, Mistakes Included, Matters to Me",
    pillar: "journey", contentType: "storytelling", angle: "Big Goal / Dream Journey", format: "Voiceover Format",
    funnelStage: "tofu", ctaType: T, conceptBucket: "proven", effort: "default",
    bodyBlack: "I could post only the wins and let people assume this all came easily. It didn't, and I'd rather not pretend it did.\nSharing the losses alongside the wins is slower and more uncomfortable, but it's a far more honest version of what building this actually looks like.\nThe goal was never to look like I had it figured out. It was to actually build something real, in front of people, mistakes and all.\nThat's the whole reason this content looks the way it does.",
    bodyRed: "Aspirational, warm tone.", bodyGreen: "On-screen text: \"wins and losses, both, on purpose\".",
    ctaLine: "Follow if you'd rather watch the real version than the polished one.",
  },
  {
    weekOffset: 39, topicTag: "Founder Journey",
    title: "The Version of This Business I'm Working Toward, Even If It Takes Years",
    pillar: "journey", contentType: "storytelling", angle: "Big Goal / Dream Journey", format: "Voiceover Format",
    funnelStage: "bofu", ctaType: B, conceptBucket: "proven", effort: "high",
    bodyBlack: "The version of this business I'm actually building toward isn't only more clients -- it's a team that can deliver this work at a scale I never could alone.\nThat means the next few years look like building systems and training people, not only taking on more projects myself.\nIt's a slower, harder path than simply maximizing this year's revenue, and I'm choosing it anyway because the long-term version is worth more.\nComment \"BUILD\" and I'll DM you the actual roadmap I'm working from.",
    bodyRed: "Aspirational, warm tone.", bodyGreen: "Comment prompt: \"Comment BUILD\".",
    ctaLine: "Comment BUILD and I'll DM you the roadmap I'm working from.",
  },
  {
    weekOffset: 40, topicTag: "Founder Journey",
    title: "What I'd Tell the Version of Myself Who Started This With Nothing",
    pillar: "journey", contentType: "storytelling", angle: "Big Goal / Dream Journey", format: "Voiceover Format",
    funnelStage: "mofu", ctaType: M, conceptBucket: "proven", effort: "default",
    bodyBlack: "If I could talk to the version of myself who started this with no clients, no track record, and no plan, I'd tell him the early doubt was normal, not a sign to stop.\nI'd tell him the slow years weren't wasted -- they were where the actual skill got built, quietly, before anyone was watching.\nI'd tell him the goal was always going to take longer than he wanted it to, and that's fine, because it's still the right goal.\nComment \"STARTED\" and I'll share the rest of what I'd tell him.",
    bodyRed: "Aspirational, warm tone.", bodyGreen: "Comment prompt: \"Comment STARTED\".",
    ctaLine: "Comment STARTED and I'll share the rest of what I'd tell him.",
  },
];
